(()=>{
const $=id=>document.getElementById(id);
const CARD_IMG={RUN:'cards/run-card.png',PASS:'cards/pass-card.png',TACKLE:'cards/tackle-card.png',INTERCEPTION:'cards/interception-card.png',BLOCK:'cards/block-card.png',BLITZ:'cards/blitz-card.png',FOOTBALL:'cards/football-card.png'};
const EFFECT={zh:{RUN:'本回合额外抽1张；之后仍要进行正常结束回合抽牌。',PASS:'查看牌库顶部3张，不能改变顺序，然后抽最上面1张。',TACKLE:'指定一名玩家，随机拿走对方1张功能牌。',INTERCEPTION:'反应牌：取消RUN、PASS或一次抽牌。',BLOCK:'反应牌：取消INTERCEPTION或TACKLE。',BLITZ:'指定一名玩家，让他立即额外抽1张。'},en:{RUN:'Draw 1 extra card this turn. You still make your normal end-turn draw later.',PASS:'Look at the top 3 cards without changing their order, then draw the top card.',TACKLE:'Choose a player and take 1 random Action Card from their hand.',INTERCEPTION:'Reaction: cancel RUN, PASS, or one draw.',BLOCK:'Reaction: cancel INTERCEPTION or TACKLE.',BLITZ:'Choose a player. That player immediately draws 1 extra card.'}};
let lang='zh',logs=[],deck=[],discard=[],hands=[[],[],[]],score=[0,0,0],turn=0,busy=false,over=false;
const pool={RUN:8,PASS:8,TACKLE:7,INTERCEPTION:7,BLOCK:7,BLITZ:5};
function L(z,e){return lang==='zh'?z:e}function who(p){return p===0?L('你','You'):`AI ${p}`}
function shuffle(a){for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function safeShuffle(a){shuffle(a);if(a.length>1&&a[0]==='FOOTBALL'){const j=1+Math.floor(Math.random()*(a.length-1));[a[0],a[j]]=[a[j],a[0]]}return a}
function makeDeck(){const a=[];for(const [k,n] of Object.entries(pool))for(let i=0;i<n;i++)a.push(k);a.push('FOOTBALL');return safeShuffle(a)}
function log(z,e){logs.push({zh:z,en:e});renderLogs()}
function renderLogs(){$('log').innerHTML=logs.map(x=>lang==='zh'?x.zh:x.en).join('<br>');$('log').scrollTop=$('log').scrollHeight}
function discardFrom(p,type){const i=hands[p].indexOf(type);if(i<0)return false;hands[p].splice(i,1);discard.push(type);return true}
function recycle(){if(deck.length<=10&&discard.length){deck.push(...discard.splice(0));safeShuffle(deck);log('♻️ 公共牌库剩余10张或更少，弃牌区已全部洗回公共牌库。','♻️ The draw pile reached 10 cards or fewer, so the entire discard pile was shuffled back in.')}}
function render(){document.documentElement.lang=lang==='zh'?'zh-CN':'en';$('back').textContent=L('← 休闲模式','← Casual Mode');$('rulesLink').textContent=L('说明书','Rulebook');$('newBtn').textContent=L('重新开始','New Game');$('langBtn').textContent=L('Switch to English','Switch to Chinese');$('goalTitle').textContent=L('胜利目标','GOAL');$('goalText').textContent=L('抽到FOOTBALL CARD获得1个🏈；随后把FOOTBALL放回公共牌库、重新洗牌，并重新抽1张。先获得3个🏈获胜。','Draw the FOOTBALL CARD to gain 1 football. Return it to the shared deck, reshuffle, then draw again. First to 3 wins.');$('turnTitle').textContent=over?L('比赛结束','GAME OVER'):(turn===0?L('你的回合','YOUR TURN'):`AI ${turn} TURN`);$('turnText').textContent=over?'':turn===0?L('你可以先使用功能牌；不再出牌时，点击“正常抽1张”结束回合。','Play Action Cards first. When finished, make your normal draw to end the turn.'):L('电脑正在行动…','Computer is playing…');$('drawBtn').textContent=L('正常抽1张并结束回合','Normal Draw & End Turn');$('drawBtn').disabled=turn!==0||busy||over;$('deckCount').textContent=L(`公共牌库：${deck.length}`,`Draw pile: ${deck.length}`);$('discardCount').textContent=L(`弃牌区：${discard.length}`,`Discard: ${discard.length}`);for(let p=0;p<3;p++){$('p'+p).classList.toggle('on',p===turn&&!over);$('s'+p).textContent=`🏈 ${score[p]} / 3`;$('c'+p).textContent=L(`${hands[p].length}张手牌`,`${hands[p].length} cards`)}$('n0').textContent=L('你','YOU');$('handTitle').textContent=L('你的手牌','YOUR HAND');const root=$('hand');root.innerHTML='';hands[0].forEach((k,i)=>{const active=turn===0&&!busy&&!over&&!['INTERCEPTION','BLOCK'].includes(k);const c=document.createElement('div');c.className='card '+(active?'':'off');c.dataset.i=i;c.dataset.card=k;c.title=`${k} · ${EFFECT[lang][k]}`;c.innerHTML=`<img src="${CARD_IMG[k]}" alt="${k} card"><span class="cardTag">${k}</span>`;if(active)c.onclick=()=>humanPlay(i,k);root.appendChild(c)});renderLogs()}
function openModal(title,body,buttons=[]){busy=true;$('mTitle').textContent=title;$('mBody').innerHTML=body;$('mActions').innerHTML='';buttons.forEach((b,i)=>{const x=document.createElement('button');x.className='btn '+(i===0?'gold':'');x.textContent=b.label;x.onclick=b.fn;$('mActions').appendChild(x)});$('modal').classList.add('show');render()}
function closeModal(){ $('modal').classList.remove('show');busy=false;render() }
function ask(title,body,yes,no){return new Promise(resolve=>openModal(title,body,[{label:yes,fn:()=>{closeModal();resolve(true)}},{label:no,fn:()=>{closeModal();resolve(false)}}]))}
function choosePlayer(title,exclude){return new Promise(resolve=>{const btns=[0,1,2].filter(x=>x!==exclude).map(p=>({label:who(p),fn:()=>{closeModal();resolve(p)}}));openModal(title,'',btns)})}
async function reactionCancel(actor,effect){if(actor===0){const ai=[1,2].find(p=>hands[p].includes('INTERCEPTION')&&Math.random()<.38);if(ai===undefined)return false;discardFrom(ai,'INTERCEPTION');log(`AI ${ai} 打出 INTERCEPTION，尝试取消 ${effect}。`,`AI ${ai} plays INTERCEPTION to cancel ${effect}.`);if(hands[0].includes('BLOCK')){const use=await ask('INTERCEPTION',L(`<p>AI ${ai} 要取消你的 ${effect}。是否使用 BLOCK？</p>`,`<p>AI ${ai} is canceling your ${effect}. Use BLOCK?</p>`),L('使用 BLOCK','Use BLOCK'),L('不用','Pass'));if(use){discardFrom(0,'BLOCK');log('你用 BLOCK 取消了 INTERCEPTION。','You use BLOCK to cancel INTERCEPTION.');return false}}return true}else{if(!hands[0].includes('INTERCEPTION'))return false;const use=await ask('INTERCEPTION',L(`<p>${who(actor)} 使用 ${effect}。要用 INTERCEPTION 取消吗？</p>`,`<p>${who(actor)} uses ${effect}. Cancel it with INTERCEPTION?</p>`),L('使用 INTERCEPTION','Use INTERCEPTION'),L('不使用','Pass'));if(!use)return false;discardFrom(0,'INTERCEPTION');if(hands[actor].includes('BLOCK')&&Math.random()<.45){discardFrom(actor,'BLOCK');log(`${who(actor)} 用 BLOCK 取消了你的 INTERCEPTION。`,`${who(actor)} uses BLOCK to cancel your INTERCEPTION.`);return false}log('INTERCEPTION 生效，效果被取消。','INTERCEPTION works and cancels the effect.');return true}}
async function reactionCancelDraw(target){if(target===0){const ai=[1,2].find(p=>hands[p].includes('INTERCEPTION')&&Math.random()<.34);if(ai===undefined)return false;discardFrom(ai,'INTERCEPTION');log(`AI ${ai} 用 INTERCEPTION 取消你的这次抽牌。`,`AI ${ai} uses INTERCEPTION to cancel your draw.`);if(hands[0].includes('BLOCK')){const use=await ask('INTERCEPTION',L('<p>你的抽牌被取消。使用 BLOCK 取消 INTERCEPTION 吗？</p>','<p>Your draw is being canceled. Use BLOCK?</p>'),L('使用 BLOCK','Use BLOCK'),L('不用','Pass'));if(use){discardFrom(0,'BLOCK');log('BLOCK 生效，你继续抽牌。','BLOCK works. Your draw continues.');return false}}return true}else{if(!hands[0].includes('INTERCEPTION'))return false;const use=await ask('INTERCEPTION',L(`<p>${who(target)} 即将抽1张。是否用 INTERCEPTION 取消这次抽牌？</p>`,`<p>${who(target)} is about to draw. Cancel this draw?</p>`),L('使用 INTERCEPTION','Use INTERCEPTION'),L('不使用','Pass'));if(!use)return false;discardFrom(0,'INTERCEPTION');if(hands[target].includes('BLOCK')&&Math.random()<.4){discardFrom(target,'BLOCK');log(`${who(target)} 用 BLOCK 取消了你的 INTERCEPTION。`,`${who(target)} uses BLOCK to cancel your INTERCEPTION.`);return false}log('INTERCEPTION 生效，这次抽牌被取消。','INTERCEPTION works. The draw is canceled.');return true}}
async function takeRaw(target){recycle();if(!deck.length)return null;const k=deck.pop();log(`${who(target)} 抽到 ${k}。`,`${who(target)} draws ${k}.`);if(k==='FOOTBALL'){score[target]++;render();log(`${who(target)} 获得1个🏈！`,`${who(target)} gains 1 football!`);if(score[target]>=3){over=true;render();openModal(L('比赛结束','GAME OVER'),`<p>${who(target)} ${L('率先获得3个🏈，获胜！','reaches 3 footballs and wins!')}</p>`,[{label:L('再来一局','Play Again'),fn:()=>{closeModal();reset()}}]);return 'WIN'}deck.push('FOOTBALL');safeShuffle(deck);log('FOOTBALL CARD 已放回公共牌库并重新洗牌；不会位于牌堆最底部。','The FOOTBALL CARD is returned and reshuffled; it will not be on the bottom of the deck.');render();await new Promise(r=>setTimeout(r,350));log('↻ 抽到FOOTBALL后，重新抽1张。','↻ After drawing FOOTBALL, draw again.');return takeRaw(target)}hands[target].push(k);render();return k}
async function drawOne(target,interceptable=true){if(interceptable&&await reactionCancelDraw(target))return 'CANCELED';return takeRaw(target)}
async function humanPlay(index,type){if(turn!==0||busy||over)return;busy=true;render();if(hands[0][index]!==type){busy=false;render();return}discardFrom(0,type);log(`你打出 ${type}。`,`You play ${type}.`);if(type==='RUN'){if(await reactionCancel(0,'RUN')){log('RUN 被 INTERCEPTION 取消。','RUN is canceled by INTERCEPTION.')}else{await drawOne(0,true)}busy=false;render();return}if(type==='PASS'){if(await reactionCancel(0,'PASS')){log('PASS 被 INTERCEPTION 取消。','PASS is canceled by INTERCEPTION.')}else{recycle();const top=[...deck].slice(-3).reverse();openModal('PASS',`<p>${L('查看顶部3张，顺序不能改变；然后抽最上面1张。','Look at the top 3 cards. Do not change their order; then draw the top card.')}</p><div class="modalCards">${top.map((k,i)=>`<img class="${i===0?'top':''}" src="${CARD_IMG[k]}" alt="${k}">`).join('')}</div>`,[{label:L('抽最上面1张','Draw Top Card'),fn:async()=>{closeModal();busy=true;await drawOne(0,true);busy=false;render()}}]);return}busy=false;render();return}if(type==='TACKLE'){const target=await choosePlayer(L('选择 TACKLE 目标','Choose TACKLE Target'),0);if(hands[target].includes('BLOCK')&&Math.random()<.42){discardFrom(target,'BLOCK');log(`${who(target)} 用 BLOCK 取消 TACKLE。`,`${who(target)} uses BLOCK to cancel TACKLE.`)}else{const candidates=hands[target].map((x,i)=>({x,i})).filter(o=>o.x!=='FOOTBALL');if(candidates.length){const pick=candidates[Math.floor(Math.random()*candidates.length)];hands[target].splice(pick.i,1);hands[0].push(pick.x);log(`你从 ${who(target)} 随机拿到 ${pick.x}。`,`You randomly take ${pick.x} from ${who(target)}.`)}else log('目标没有可拿走的功能牌。','The target has no Action Card to take.')}busy=false;render();return}if(type==='BLITZ'){const target=await choosePlayer(L('选择 BLITZ 目标','Choose BLITZ Target'),0);await drawOne(target,true);busy=false;render();return}}
async function aiTurn(p){if(over)return;busy=true;render();await new Promise(r=>setTimeout(r,550));const playable=hands[p].filter(x=>['RUN','PASS','TACKLE','BLITZ'].includes(x));if(playable.length&&Math.random()<.72){const type=playable[Math.floor(Math.random()*playable.length)];discardFrom(p,type);log(`${who(p)} 打出 ${type}。`,`${who(p)} plays ${type}.`);if(type==='RUN'){if(!await reactionCancel(p,'RUN'))await drawOne(p,true)}else if(type==='PASS'){if(!await reactionCancel(p,'PASS'))await drawOne(p,true)}else if(type==='TACKLE'){const target=[0,1,2].filter(x=>x!==p)[Math.floor(Math.random()*2)];if(target===0&&hands[0].includes('BLOCK')){const use=await ask('TACKLE',L(`<p>${who(p)} 对你使用 TACKLE。要用 BLOCK 取消吗？</p>`,`<p>${who(p)} uses TACKLE on you. Use BLOCK?</p>`),L('使用 BLOCK','Use BLOCK'),L('不用','Pass'));if(use){discardFrom(0,'BLOCK');log('你用 BLOCK 取消 TACKLE。','You use BLOCK to cancel TACKLE.')}else aiSteal(p,target)}else if(hands[target].includes('BLOCK')&&Math.random()<.4){discardFrom(target,'BLOCK');log(`${who(target)} 用 BLOCK 取消 TACKLE。`,`${who(target)} uses BLOCK to cancel TACKLE.`)}else aiSteal(p,target)}else if(type==='BLITZ'){const target=[0,1,2].filter(x=>x!==p)[Math.floor(Math.random()*2)];await drawOne(target,true)}}if(!over){await drawOne(p,true);if(!over){turn=(turn+1)%3;busy=false;render();if(turn!==0)setTimeout(()=>aiTurn(turn),650)}}}
function aiSteal(p,target){if(!hands[target].length){log(`${who(target)} 没有可拿走的功能牌。`,`${who(target)} has no Action Card to take.`);return}const i=Math.floor(Math.random()*hands[target].length),k=hands[target].splice(i,1)[0];hands[p].push(k);log(`${who(p)} 从 ${who(target)} 随机拿走 ${k}。`,`${who(p)} randomly takes ${k} from ${who(target)}.`)}
async function normalDraw(){if(turn!==0||busy||over)return;busy=true;render();await drawOne(0,true);if(over)return;turn=1;busy=false;render();setTimeout(()=>aiTurn(1),650)}
function reset(){deck=makeDeck();discard=[];hands=[[],[],[]];score=[0,0,0];turn=0;busy=false;over=false;$('modal').classList.remove('show');logs=[];for(let p=0;p<3;p++)for(let n=0;n<5;n++){let k=deck.pop();while(k==='FOOTBALL'){deck.unshift(k);safeShuffle(deck);k=deck.pop()}hands[p].push(k)}log('游戏开始：抽到FOOTBALL是好事，先获得3个🏈获胜。','Game start: drawing FOOTBALL is good. First to 3 footballs wins.');render()}
function showLegend(){const order=['FOOTBALL','RUN','PASS','TACKLE','INTERCEPTION','BLOCK','BLITZ'];openModal(L('卡牌规则','Card Rules'),`<div class="cardLegend">${order.map(k=>`<div class="legendItem"><img src="${CARD_IMG[k]}" alt="${k}"><div><b>${k}</b><br><span>${k==='FOOTBALL'?L('抽到后+1🏈，洗回牌库并重新抽1张。','Gain 1 football, shuffle it back, then draw again.'):EFFECT[lang][k]}</span></div></div>`).join('')}</div>`,[{label:L('关闭','Close'),fn:closeModal}])}
$('drawBtn').onclick=normalDraw;$('deck').onclick=normalDraw;$('newBtn').onclick=reset;$('rulesBtn').onclick=showLegend;$('langBtn').onclick=()=>{lang=lang==='zh'?'en':'zh';render()};reset();
})();