(()=>{
const $=id=>document.getElementById(id);
const POOLS={2:{RUN:6,PASS:6,TACKLE:5,INTERCEPTION:3,BLOCK:5,BLITZ:3},3:{RUN:8,PASS:8,TACKLE:7,INTERCEPTION:4,BLOCK:7,BLITZ:4},4:{RUN:10,PASS:10,TACKLE:9,INTERCEPTION:5,BLOCK:9,BLITZ:5}};
const HAND={2:7,3:6,4:5};
const ICON={RUN:'🏃',PASS:'🎯',TACKLE:'💥',INTERCEPTION:'🦅',BLOCK:'🛡️',BLITZ:'⚡'};
const YARDS=[50,40,30,20,10];
const G={size:2,mode:'single',lang:'zh',players:[],deck:[],discard:[],currentTeam:'red',currentIndex:0,holderId:null,redProgress:0,blueProgress:0,redBalls:0,blueBalls:0,round:1,firstTeam:'red',phase:'setup',activeTeam:null,pending:null};

const TXT={
 zh:{rules:'玩法说明',reset:'重新设置',sub:'橄榄球比赛现场版 · 单人演示 / 多人本地操作',stadium:'真实美式橄榄球比赛现场视角',redEnd:'红队端区',blueEnd:'蓝队端区',drive:'4次成功 = TOUCHDOWN · 50为起点 · 第4次成功到10后自动冲入END ZONE',redPos:'红队推进位置',bluePos:'蓝队推进位置',quick:'快速换人',tip:'50是起点 · 第4次成功直接达阵',playHint:'当前操作提示固定在手牌上方。换球员后不用滚到页面底部。',log:'对局记录',footer:'单人演示：可操作双方。<br>多人本地：换边时会遮挡屏幕并提示交接设备。',start:'开始游戏',size:'选择人数模式',sizeDesc:'2v2：每人7张 / 3v3：每人6张 / 4v4：每人5张',view:'选择操作模式',single:'单人演示',multi:'多人本地操作',viewDesc:'多人本地操作会在换边时遮挡画面，让下一方再查看自己的手牌。',enter:'开始进入比赛现场',rulesTitle:'界面说明',close:'关闭',ready:'我已准备好，显示手牌',skillTitle:'QUARTERBACK 身份技能',useSkill:'使用技能（立即消耗）',skipSkill:'暂不使用',next:'下一个人',prev:'上一个人',mode:'模式',role:'身份',skill:'技能状态',team:'队伍',used:'已使用',available:'可用',none:'无主动技能',cards:'张',currentHand:'当前手牌',current:'当前',deck:'牌库',holder:'当前持球者',chooseHolder:'选择持球者',attack:'进攻时刻',defense:'防守时刻',block:'BLOCK反制',finalBlitz:'BLITZ最终反制',touchdownRun:'冲入端区',gameover:'比赛结束',noDefense:'不防守',noBlock:'不用 BLOCK',skipBlitz:'放弃 BLITZ',red:'红队',blue:'蓝队',player:'球员',turn:'操作',nextRound:'继续下一回合',gameOverBtn:'比赛结束'},
 en:{rules:'Rules',reset:'Reset',sub:'American Football Stadium Edition · Solo Demo / Local Multiplayer',stadium:'Real American Football Stadium View',redEnd:'RED END ZONE',blueEnd:'BLUE END ZONE',drive:'4 successful plays = TOUCHDOWN · Start at 50 · 4th success reaches 10 then auto-runs into END ZONE',redPos:'Red Team Field Position',bluePos:'Blue Team Field Position',quick:'Quick Switch',tip:'50 is the start · 4th success scores',playHint:'Action prompts stay above the hand. You do not need to scroll down after switching players.',log:'Match Log',footer:'Solo Demo: control both teams.<br>Local Multiplayer: the screen is covered during team handoff.',start:'Start Game',size:'Choose Team Size',sizeDesc:'2v2: 7 cards each / 3v3: 6 cards each / 4v4: 5 cards each',view:'Choose Play Mode',single:'Solo Demo',multi:'Local Multiplayer',viewDesc:'Local Multiplayer hides the screen during team handoff so the next side can view its own hand.',enter:'Enter the Stadium',rulesTitle:'How This Version Works',close:'Close',ready:'Ready — Show Hand',skillTitle:'QUARTERBACK Skill',useSkill:'Use Skill (consumed immediately)',skipSkill:'Skip Skill',next:'Next Player',prev:'Previous Player',mode:'Mode',role:'Role',skill:'Skill',team:'Team',used:'Used',available:'Available',none:'No active skill',cards:'cards',currentHand:'Current Hand',current:'Current',deck:'Deck',holder:'Current Ball Carrier',chooseHolder:'Choose Ball Carrier',attack:'Offense',defense:'Defense',block:'BLOCK Response',finalBlitz:'Final BLITZ',touchdownRun:'Run to End Zone',gameover:'Game Over',noDefense:'No Defense',noBlock:'No BLOCK',skipBlitz:'Skip BLITZ',red:'Red Team',blue:'Blue Team',player:'Player',turn:'turn',nextRound:'Next Round',gameOverBtn:'Game Over'}
};
const tx=k=>TXT[G.lang][k]||k;
const teamName=t=>t==='red'?tx('red'):tx('blue');
const label=p=>G.lang==='zh'?`${teamName(p.team)}${p.num}号`:`${teamName(p.team)} #${p.num}`;
const roleName=r=>r==='QB'?'QB':tx('player');
const desc=t=>({zh:{RUN:'持球推进',PASS:'传给队友',TACKLE:'阻止 RUN',INTERCEPTION:'抄截 PASS',BLOCK:'抵消防守',BLITZ:'强力突袭'},en:{RUN:'advance the ball',PASS:'pass to a teammate',TACKLE:'stop a RUN',INTERCEPTION:'intercept a PASS',BLOCK:'counter a defense',BLITZ:'aggressive pressure'}}[G.lang][t]);
const shuffle=a=>{for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const byId=id=>G.players.find(p=>p.id===id);
const teamPlayers=t=>G.players.filter(p=>p.team===t);
const currentPlayer=()=>G.players[G.currentIndex];
const holder=()=>byId(G.holderId);
const idx=id=>G.players.findIndex(p=>p.id===id);
const balls=n=>[0,1,2].map(i=>i<n?'🏈':'⚪').join(' ');
const progress=t=>t==='red'?G.redProgress:G.blueProgress;
const setProgress=(t,v)=>{if(t==='red')G.redProgress=v;else G.blueProgress=v};
const yard=t=>YARDS[Math.min(4,Math.max(0,progress(t)))];
const driveX=t=>{let p=Math.min(4,Math.max(0,progress(t)));return t==='red'?[50,58,66,74,82][p]:[50,42,34,26,18][p]};
const driveTeam=()=>holder()?.team||G.activeTeam||G.firstTeam||'red';
const hasOffense=p=>p&&(p.hand.includes('RUN')||p.hand.includes('PASS'));
const teamHasOffense=t=>teamPlayers(t).some(hasOffense);
function addLog(html){let d=document.createElement('div');d.className='logItem';d.innerHTML=html;$('log').prepend(d)}
function buildDeck(){let d=[];Object.entries(POOLS[G.size]).forEach(([t,n])=>{for(let i=0;i<n;i++)d.push(t)});return shuffle(d)}
function consume(p,t){let i=p.hand.indexOf(t);if(i<0)return false;p.hand.splice(i,1);G.discard.push(t);return true}

function updateStatic(){
 document.documentElement.lang=G.lang==='zh'?'zh-CN':'en';
 $('subtitleText').textContent=tx('sub');$('rulesBtn').textContent=tx('rules');$('restartBtn').textContent=tx('reset');$('langToggleBtn').textContent='中文 / EN';
 $('stadiumTitle').textContent=tx('stadium');$('leftEndzone').textContent=tx('redEnd');$('rightEndzone').textContent=tx('blueEnd');$('driveHint').textContent=tx('drive');
 $('redTeamTitle').textContent=tx('redPos');$('blueTeamTitle').textContent=tx('bluePos');$('playerSwitchLabel').textContent=tx('quick');$('ruleChip').textContent=tx('tip');$('playHint').textContent=tx('playHint');$('logTitle').textContent=tx('log');$('footerNote').innerHTML=tx('footer');
 $('setupTitle').textContent=tx('start');$('sizeTitle').textContent=tx('size');$('sizeDesc').textContent=tx('sizeDesc');$('viewTitle').textContent=tx('view');$('singleModeBtn').textContent=tx('single');$('multiModeBtn').textContent=tx('multi');$('viewDesc').textContent=tx('viewDesc');$('startBtn').textContent=tx('enter');
 $('rulesHeading').textContent=tx('rulesTitle');$('closeRulesBtn').textContent=tx('close');$('privacyConfirmBtn').textContent=tx('ready');$('skillHeading').textContent=tx('skillTitle');$('useSkillBtn').textContent=tx('useSkill');$('skipSkillBtn').textContent=tx('skipSkill');$('prevBtn').textContent=tx('prev');$('nextBtn').textContent=tx('next');
 $('rulesBody').innerHTML=G.lang==='zh'?`<b>系统自动判定攻防：</b><br>1. RUN / PASS 成功后系统自动推进；失败不推进。<br>2. RUN 可被 TACKLE / BLITZ 阻止。<br>3. PASS 可被 INTERCEPTION / BLITZ 阻止；INTERCEPTION 成功后防守球员直接获得球权。<br>4. TACKLE / INTERCEPTION 后进攻方可用 BLOCK；BLOCK 后防守方仍可用 BLITZ 最终反制。<br>5. QB 打出 PASS 后可选择是否使用身份技能；点击使用即立即消耗。<br>6. 每队从50码开始：第1次成功到40，第2次到30，第3次到20，第4次到10并自动冲入END ZONE。<br>7. 4次成功=TOUCHDOWN=1个🏈；先获得3个🏈获胜。`:`<b>System-based attack/defense resolution:</b><br>1. Successful RUN/PASS automatically advances the drive; failed plays do not advance.<br>2. RUN can be stopped by TACKLE or BLITZ.<br>3. PASS can be stopped by INTERCEPTION or BLITZ; a successful INTERCEPTION gives the defender possession.<br>4. After TACKLE/INTERCEPTION, the offense may use BLOCK; after BLOCK, the defense may still use BLITZ as the final response.<br>5. When a QB plays PASS, the player may choose whether to use the identity skill; choosing Use consumes it immediately.<br>6. Each team starts at the 50: 1st success→40, 2nd→30, 3rd→20, 4th→10 and the runner automatically enters the END ZONE.<br>7. 4 successful plays = TOUCHDOWN = 1 🏈; first to 3 🏈 wins.`;
}
function phaseText(){return ({chooseHolder:tx('chooseHolder'),attack:tx('attack'),skill:tx('skill'),defense:tx('defense'),block:tx('block'),blitzAfterBlock:tx('finalBlitz'),touchdownRun:tx('touchdownRun'),gameover:tx('gameover')})[G.phase]||''}
function createGame(){
 G.players=[];G.deck=buildDeck();G.discard=[];G.currentTeam='red';G.currentIndex=0;G.holderId=null;G.redProgress=G.blueProgress=G.redBalls=G.blueBalls=0;G.round=1;G.firstTeam='red';G.pending=null;
 for(let i=0;i<G.size;i++)G.players.push({id:`R${i+1}`,team:'red',num:i+1,role:'PLAYER',revealed:true,skillUsed:false,hand:[]});
 for(let i=0;i<G.size;i++)G.players.push({id:`B${i+1}`,team:'blue',num:i+1,role:'PLAYER',revealed:false,skillUsed:false,hand:[]});
 G.players[Math.floor(Math.random()*G.size)].role='QB';G.players[G.size+Math.floor(Math.random()*G.size)].role='QB';
 for(let r=0;r<HAND[G.size];r++)for(const p of G.players){let c=G.deck.pop();if(c)p.hand.push(c)}
 G.phase='chooseHolder';G.activeTeam='red';$('log').innerHTML='';
 addLog(G.lang==='zh'?`<b>开始：</b>${G.size}v${G.size}。50码为起点，第4次成功直接达阵。`:`<b>Start:</b> ${G.size}v${G.size}. The 50-yard line is the starting point; the 4th successful play scores.`);
 handoff('red',G.lang==='zh'?'红队先攻':'Red Team attacks first',G.lang==='zh'?'请选择一名有 RUN / PASS 的红队球员作为持球者。':'Choose a Red Team player with RUN or PASS as the ball carrier.');
}
function collectRedeal(){let pool=[...G.deck,...G.discard];for(const p of G.players){pool.push(...p.hand);p.hand=[]}G.deck=shuffle(pool);G.discard=[];for(let r=0;r<HAND[G.size];r++)for(const p of G.players){let c=G.deck.pop();if(c)p.hand.push(c)}}

function renderField(){
 const root=$('fieldPlayers');root.innerHTML='';const off=driveTeam(),def=off==='red'?'blue':'red',line=driveX(off),dir=off==='red'?1:-1,ys={2:[35,62],3:[24,50,76],4:[18,38,58,78]}[G.size];
 $('scrimmageLine').style.left=line+'%';$('scrimmageBadge').style.left=line+'%';$('scrimmageBadge').textContent=`${teamName(off)} · BALL ON ${yard(off)}`;
 for(const p of teamPlayers(off)){let i=p.num-1,d=document.createElement('div'),ball=p.id===G.holderId,x=ball?line:line-dir*(5+(i%2)*2),role=(p.team===G.currentTeam||p.revealed)?roleName(p.role):'?';x=Math.max(10,Math.min(90,x));d.id='fieldPlayer_'+p.id;d.className=`player ${p.team} ${p.id===currentPlayer()?.id?'active':''} ${ball?'ball':''}`;d.style.left=`calc(${x}% - 36px)`;d.style.top=`calc(${ys[i]}% - 36px)`;d.innerHTML=`${ball?'<div class="ballIcon">🏈</div>':''}<div class="num">${p.num}</div><div class="role">${role}</div>`;d.onclick=()=>switchTo(p);root.appendChild(d)}
 for(const p of teamPlayers(def)){let i=p.num-1,d=document.createElement('div'),ball=p.id===G.holderId,x=ball?driveX(p.team):line+dir*(6+(i%2)*2),role=(p.team===G.currentTeam||p.revealed)?roleName(p.role):'?';x=Math.max(10,Math.min(90,x));d.id='fieldPlayer_'+p.id;d.className=`player ${p.team} ${p.id===currentPlayer()?.id?'active':''} ${ball?'ball':''}`;d.style.left=`calc(${x}% - 36px)`;d.style.top=`calc(${ys[i]}% - 36px)`;d.innerHTML=`${ball?'<div class="ballIcon">🏈</div>':''}<div class="num">${p.num}</div><div class="role">${role}</div>`;d.onclick=()=>switchTo(p);root.appendChild(d)}
}
function renderBottom(){let h=holder();$('redProg').textContent=yard('red')+' YD';$('blueProg').textContent=yard('blue')+' YD';$('redFill').style.width=G.redProgress*25+'%';$('blueFill').style.width=G.blueProgress*25+'%';$('redBalls').textContent=balls(G.redBalls);$('blueBalls').textContent=balls(G.blueBalls);$('holderText').textContent=`🏈 ${tx('holder')}: ${h?label(h):'--'}`;$('roundText').textContent=G.lang==='zh'?`第 ${G.round} 回合 · ${teamName(G.firstTeam)}先攻 · ${phaseText()} · ${teamName(driveTeam())}推进到 ${yard(driveTeam())}码`:`Round ${G.round} · ${teamName(G.firstTeam)} attacks first · ${phaseText()} · ${teamName(driveTeam())} at the ${yard(driveTeam())}-yard line`}
function allowed(p,t){if(!p||p.team!==G.currentTeam)return false;if(G.phase==='attack'&&G.activeTeam===p.team&&p.id===G.holderId)return t==='RUN'||t==='PASS';if(G.phase==='defense'&&G.activeTeam===p.team)return G.pending.action==='RUN'?['TACKLE','BLITZ'].includes(t):['INTERCEPTION','BLITZ'].includes(t);if(G.phase==='block'&&G.activeTeam===p.team)return t==='BLOCK';if(G.phase==='blitzAfterBlock'&&G.activeTeam===p.team)return t==='BLITZ';return false}
function renderHand(){let p=currentPlayer();if(!p)return;$('currentPlayerText').textContent=`${tx('currentHand')}: ${label(p)}`;$('viewModeChip').textContent=`${tx('mode')}: ${G.mode==='multi'?tx('multi'):tx('single')}`;$('roleChip').textContent=`${tx('role')}: ${roleName(p.role)}`;$('skillChip').textContent=`${tx('skill')}: ${p.role==='QB'?(p.skillUsed?tx('used'):tx('available')):tx('none')}`;$('teamChip').textContent=`${tx('team')}: ${teamName(p.team)}`;let root=$('hand');root.innerHTML='';let total=p.hand.length;p.hand.forEach((t,i)=>{let c=document.createElement('div'),mid=(total-1)/2,rot=(i-mid)*5,lift=Math.abs(i-mid)*2.5;c.className=`card ${t.toLowerCase()} ${allowed(p,t)?'':'disabled'}`;c.style.setProperty('--rot',rot+'deg');c.style.transform=`rotate(${rot}deg) translateY(${lift}px)`;c.style.zIndex=10+i;c.innerHTML=`<div><div class="icon">${ICON[t]}</div><div class="name">${t}</div></div><div class="desc">${desc(t)}</div>`;if(allowed(p,t))c.onclick=()=>playCard(p,t);root.appendChild(c)})}
function renderSwitch(){let root=$('switchList');root.innerHTML='';for(const p of teamPlayers(G.currentTeam)){let b=document.createElement('button'),i=idx(p.id);b.className=`switchBtn ${i===G.currentIndex?'active':''}`;b.innerHTML=`<b>${label(p)}</b><small>${roleName(p.role)} · ${p.hand.length} ${tx('cards')}</small>`;b.onclick=()=>{G.currentIndex=i;renderAll()};root.appendChild(b)}}
function renderTop(){$('modeText').textContent=`${G.size}v${G.size} · ${G.mode==='multi'?tx('multi'):tx('single')} · ${tx('drive')}`;$('turnTag').textContent=`${tx('current')}: ${teamName(G.currentTeam)} · ${phaseText()}`;$('deckTag').textContent=`${tx('deck')}: ${G.deck.length}`;$('activeModeTag').textContent=`${teamName(G.activeTeam||G.currentTeam)} ${tx('turn')}`}
function showActions(title,arr){$('actionTitle').textContent=title;let r=$('actionButtons');r.innerHTML='';$('actionPanel').classList.remove('hidden');for(const x of arr){let b=document.createElement('button');b.className='btn '+(x.primary?'primary':'');b.textContent=x.label;b.onclick=x.fn;r.appendChild(b)}}
function hideActions(){$('actionPanel').classList.add('hidden');$('actionButtons').innerHTML=''}
function renderActions(){hideActions();if(G.phase==='chooseHolder'&&G.activeTeam===G.currentTeam){let ps=teamPlayers(G.activeTeam).filter(hasOffense);showActions(tx('chooseHolder'),ps.map((p,i)=>({label:`🏈 ${label(p)}`,primary:i===0,fn:()=>chooseHolder(p)})))}else if(G.phase==='defense'&&G.activeTeam===G.currentTeam)showActions(G.lang==='zh'?`对方发动 ${G.pending.action}`:`Opponent used ${G.pending.action}`,[{label:tx('noDefense'),fn:resolveAttackSuccess}]);else if(G.phase==='block'&&G.activeTeam===G.currentTeam)showActions(G.lang==='zh'?`对方使用 ${G.pending.defense}`:`Opponent played ${G.pending.defense}`,[{label:tx('noBlock'),fn:resolveNormalDefense}]);else if(G.phase==='blitzAfterBlock'&&G.activeTeam===G.currentTeam)showActions(G.lang==='zh'?'对方已经使用 BLOCK':'Opponent has used BLOCK',[{label:tx('skipBlitz'),fn:resolveAttackSuccess}])}
function renderAll(){if(!G.players.length)return;renderField();renderBottom();renderHand();renderSwitch();renderTop();renderActions()}
function firstIndex(t){let p=teamPlayers(t)[0];return p?idx(p.id):0}
function handoff(team,title,text,after){G.currentTeam=team;G.currentIndex=firstIndex(team);if(G.mode==='multi'){$('privacyTitle').textContent=title||teamName(team);$('privacyText').textContent=text||'';$('privacyModal').classList.add('show');$('privacyConfirmBtn').onclick=()=>{$('privacyModal').classList.remove('show');renderAll();if(after)after()}}else{renderAll();if(after)after()}}
function switchTo(p){if(p.team!==G.currentTeam)return;G.currentIndex=idx(p.id);renderAll()}
function cycle(dir){let a=teamPlayers(G.currentTeam).map(p=>idx(p.id)),i=a.indexOf(G.currentIndex);if(i<0)i=0;G.currentIndex=a[(i+dir+a.length)%a.length];renderAll()}
function chooseHolder(p){G.holderId=p.id;G.phase='attack';G.activeTeam=p.team;G.currentIndex=idx(p.id);addLog(G.lang==='zh'?`<b>持球：</b>${label(p)} 成为持球者。`:`<b>Ball Carrier:</b> ${label(p)} has the ball.`);renderAll()}

function playCard(p,t){
 if(G.phase==='attack'){
  if(!consume(p,t))return;
  if(t==='PASS'){let targets=teamPlayers(p.team).filter(x=>x.id!==p.id);showActions(G.lang==='zh'?'PASS 给哪名队友？':'Choose a PASS target',targets.map((x,i)=>({label:label(x),primary:i===0,fn:()=>passTarget(p,x)})))}
  else{G.pending={team:p.team,attacker:p.id,action:'RUN',target:p.id,skillArmed:false};addLog(`<b>${label(p)}:</b> RUN`);goDefense()}
 }else if(G.phase==='defense'){
  if(!consume(p,t))return;G.pending.defender=p.id;G.pending.defense=t;addLog(`<b>${label(p)}:</b> ${t}`);if(t==='BLITZ'){resolveFail(blitzReason());return}let atk=G.pending.team;G.phase='block';G.activeTeam=atk;handoff(atk,G.lang==='zh'?`轮到${teamName(atk)}反制`:`${teamName(atk)} response`,G.lang==='zh'?`对方使用了 ${t}。可以使用 BLOCK，或者接受防守。`:`Opponent played ${t}. Use BLOCK or accept the defense.`)
 }else if(G.phase==='block'){
  if(t!=='BLOCK'||!consume(p,t))return;addLog(`<b>${label(p)}:</b> BLOCK`);let def=p.team==='red'?'blue':'red';G.phase='blitzAfterBlock';G.activeTeam=def;handoff(def,G.lang==='zh'?`轮到${teamName(def)}最终反制`:`${teamName(def)} final response`,G.lang==='zh'?'BLOCK 已使用，仍可使用 BLITZ。':'BLOCK was used; BLITZ is still available.')
 }else if(G.phase==='blitzAfterBlock'){
  if(t!=='BLITZ'||!consume(p,t))return;addLog(`<b>${label(p)}:</b> BLITZ`);resolveFail(blitzReason())
 }
}
function passTarget(p,target){hideActions();G.pending={team:p.team,attacker:p.id,action:'PASS',target:target.id,skillArmed:false};addLog(`<b>${label(p)}:</b> PASS → ${label(target)}`);if(p.role==='QB'&&!p.skillUsed){G.phase='skill';G.activeTeam=p.team;$('skillText').textContent=G.lang==='zh'?`${label(p)} 刚刚打出 PASS。是否使用身份卡技能？点击使用后立即消耗，即使最后被 INTERCEPTION / BLITZ 阻止也不会返还。`:`${label(p)} just played PASS. Use the QB skill? It is consumed immediately even if the play is later stopped.`;$('skillModal').classList.add('show');renderAll()}else goDefense()}
function skillDecision(use){let a=byId(G.pending.attacker);G.pending.skillArmed=use;if(use){a.skillUsed=true;addLog(G.lang==='zh'?`<b>身份技能：</b>${label(a)} 使用 QB 技能，立即消耗。`:`<b>QB Skill:</b> ${label(a)} uses the skill; it is consumed immediately.`)}else addLog(G.lang==='zh'?`<b>身份技能：</b>${label(a)} 暂不使用。`:`<b>QB Skill:</b> ${label(a)} does not use the skill.`);$('skillModal').classList.remove('show');goDefense()}
function goDefense(){let def=G.pending.team==='red'?'blue':'red';G.phase='defense';G.activeTeam=def;handoff(def,G.lang==='zh'?`轮到${teamName(def)}防守`:`${teamName(def)} on defense`,G.lang==='zh'?`${teamName(G.pending.team)}刚刚打出 ${G.pending.action}。请选择防守牌或“不防守”。`:`${teamName(G.pending.team)} played ${G.pending.action}. Choose a defense card or No Defense.`)}
function blitzReason(){let a=byId(G.pending.attacker);return a.role==='QB'&&a.revealed?(G.lang==='zh'?'SACK：BLITZ 擒杀已暴露 QB。':'SACK: BLITZ brings down the revealed QB.'):(G.lang==='zh'?'BLITZ 终止本次进攻。':'BLITZ stops the play.')}
function resolveNormalDefense(){if(G.pending.defense==='TACKLE')resolveFail(G.lang==='zh'?'TACKLE 阻止 RUN；原持球者继续持球。':'TACKLE stops the RUN; the original ball carrier keeps possession.');else{let d=byId(G.pending.defender);if(G.pending.skillArmed)addLog(G.lang==='zh'?'<b>QB技能：</b>PASS 被抄截，技能已消耗，不返还。':'<b>QB Skill:</b> The PASS was intercepted; the skill is not refunded.');G.holderId=d.id;G.pending=null;G.phase='attack';G.activeTeam=d.team;addLog(G.lang==='zh'?`<b>INTERCEPTION：</b>${label(d)} 抄截成功并获得球权。`:`<b>INTERCEPTION:</b> ${label(d)} gains possession.`);handoff(d.team,`INTERCEPTION · ${teamName(d.team)}`,G.lang==='zh'?`${label(d)} 现在持球。`:`${label(d)} now has the ball.`,()=>{G.currentIndex=idx(d.id);renderAll();afterPlay()})}}
function resolveAttackSuccess(){let x=G.pending,a=byId(x.attacker),gain=1;if(x.action==='PASS'){if(a.role==='QB'&&!a.revealed){a.revealed=true;addLog(G.lang==='zh'?`<b>身份暴露：</b>${label(a)} 是 QB。`:`<b>Identity Revealed:</b> ${label(a)} is the QB.`)}if(x.skillArmed){gain=2;addLog(G.lang==='zh'?'<b>QB技能生效：</b>PASS 成功，本次推进2格。':'<b>QB Skill:</b> PASS succeeded; advance 2 spaces.')}G.holderId=x.target}else G.holderId=a.id;let before=progress(a.team),after=Math.min(4,before+gain);setProgress(a.team,after);let from=YARDS[before],to=YARDS[after];addLog(after>=4?(G.lang==='zh'?`<b>进攻成功：</b>${teamName(a.team)}从 ${from} 推进到10码线，准备冲入端区！`:`<b>Successful Play:</b> ${teamName(a.team)} advances from ${from} to the 10-yard line and is ready to enter the end zone!`):(G.lang==='zh'?`<b>进攻成功：</b>${teamName(a.team)}从 ${from} 推进到 ${to}。`:`<b>Successful Play:</b> ${teamName(a.team)} advances from ${from} to ${to}.`));G.pending=null;G.phase=after>=4?'touchdownRun':'attack';G.activeTeam=a.team;renderAll();if(after>=4){setTimeout(()=>touchdown(a.team),420);return}handoff(a.team,G.lang==='zh'?`${teamName(a.team)}推进成功 · BALL ON ${to}`:`${teamName(a.team)} advances · BALL ON ${to}`,G.lang==='zh'?`${label(holder())} 当前持球，继续进攻。`:`${label(holder())} keeps the ball.`,()=>{G.currentIndex=idx(G.holderId);renderAll();afterPlay()})}
function resolveFail(reason){let x=G.pending,a=byId(x.attacker);if(x.action==='PASS'&&x.skillArmed)addLog(G.lang==='zh'?'<b>QB技能：</b>PASS失败，但技能已消耗，不返还。':'<b>QB Skill:</b> PASS failed; the skill remains consumed.');addLog(G.lang==='zh'?`<b>进攻失败：</b>${reason}`:`<b>Failed Play:</b> ${reason}`);G.holderId=a.id;G.pending=null;G.phase='attack';G.activeTeam=a.team;handoff(a.team,G.lang==='zh'?`${teamName(a.team)}仍持球`:`${teamName(a.team)} keeps possession`,G.lang==='zh'?`${label(a)} 继续持球。`:`${label(a)} keeps the ball.`,()=>{G.currentIndex=idx(a.id);renderAll();afterPlay()})}
function afterPlay(){if(hasOffense(holder()))return;let from=holder()?.team||G.activeTeam,other=from==='red'?'blue':'red';if(!teamHasOffense(from)&&!teamHasOffense(other)){addLog(G.lang==='zh'?'<b>回合结束：</b>双方都没有 RUN/PASS。':'<b>Round End:</b> Neither team has RUN/PASS left.');endRound();return}if(teamHasOffense(other)){G.holderId=null;G.phase='chooseHolder';G.activeTeam=other;handoff(other,G.lang==='zh'?`球权交给${teamName(other)}`:`Possession goes to ${teamName(other)}`,G.lang==='zh'?`请选择${teamName(other)}新的持球者。`:`Choose a new ball carrier for ${teamName(other)}.`);return}if(teamHasOffense(from)){G.holderId=null;G.phase='chooseHolder';G.activeTeam=from;handoff(from,tx('chooseHolder'),G.lang==='zh'?`${teamName(from)}其他球员仍有 RUN/PASS。`:`Other ${teamName(from)} players still have RUN/PASS.`)}}
function touchdown(team){let runner=holder();G.phase='touchdownRun';G.activeTeam=team;renderAll();let el=runner?$('fieldPlayer_'+runner.id):null;if(el){let end=team==='red'?91:9;requestAnimationFrame(()=>{el.classList.add('tdRunner');el.style.left=`calc(${end}% - 36px)`})}setTimeout(()=>{if(team==='red')G.redBalls++;else G.blueBalls++;$('touchdownTeam').textContent=G.lang==='zh'?`${teamName(team)} · 达阵成功！`:`${teamName(team)} · TOUCHDOWN!`;$('touchdownRoute').innerHTML=G.lang==='zh'?`起点50 → 第1次40 → 第2次30 → 第3次20 → 第4次10 → <b>自动冲入 END ZONE</b><br>${runner?label(runner):'持球者'} 获得1个🏈`:`Start 50 → 1st 40 → 2nd 30 → 3rd 20 → 4th 10 → <b>auto-run into the END ZONE</b><br>${runner?label(runner):'Ball carrier'} earns 1 🏈`;$('touchdownModal').classList.add('show');renderBottom();let won=(team==='red'?G.redBalls:G.blueBalls)>=3;$('touchdownContinueBtn').textContent=won?tx('gameOverBtn'):tx('nextRound');$('touchdownContinueBtn').onclick=()=>{$('touchdownModal').classList.remove('show');setProgress(team,0);if(won){G.phase='gameover';G.activeTeam=null;renderAll();addLog(G.lang==='zh'?`<b>比赛结束：</b>${teamName(team)}率先获得3个🏈，获胜！`:`<b>Game Over:</b> ${teamName(team)} is first to 3 🏈 and wins!`);return}endRound()}},980)}
function endRound(){collectRedeal();G.round++;G.firstTeam=G.firstTeam==='red'?'blue':'red';G.holderId=null;G.pending=null;G.phase='chooseHolder';G.activeTeam=G.firstTeam;addLog(G.lang==='zh'?`<b>新回合：</b>第${G.round}回合由${teamName(G.firstTeam)}先攻。`:`<b>New Round:</b> Round ${G.round}, ${teamName(G.firstTeam)} attacks first.`);handoff(G.firstTeam,G.lang==='zh'?`第${G.round}回合 · ${teamName(G.firstTeam)}先攻`:`Round ${G.round} · ${teamName(G.firstTeam)} attacks first`,G.lang==='zh'?'请选择新的持球者。':'Choose a new ball carrier.')}

function start(){createGame();$('setupModal').classList.remove('show');updateStatic();renderAll()}
document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-size]').forEach(x=>x.classList.remove('active'));b.classList.add('active');G.size=Number(b.dataset.size)});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');G.mode=b.dataset.view});
$('startBtn').onclick=start;$('restartBtn').onclick=()=>location.reload();$('langToggleBtn').onclick=()=>{G.lang=G.lang==='zh'?'en':'zh';updateStatic();if(G.players.length)renderAll()};$('rulesBtn').onclick=()=>$('rulesModal').classList.add('show');$('closeRulesBtn').onclick=()=>$('rulesModal').classList.remove('show');$('rulesModal').onclick=e=>{if(e.target===$('rulesModal'))$('rulesModal').classList.remove('show')};$('nextBtn').onclick=()=>cycle(1);$('prevBtn').onclick=()=>cycle(-1);$('useSkillBtn').onclick=()=>skillDecision(true);$('skipSkillBtn').onclick=()=>skillDecision(false);
updateStatic();$('modeText').textContent=tx('drive');
})();