(()=>{
const $=id=>document.getElementById(id);
const POOLS={2:{RUN:6,PASS:6,TACKLE:5,INTERCEPTION:3,BLOCK:5,BLITZ:3},3:{RUN:8,PASS:8,TACKLE:7,INTERCEPTION:4,BLOCK:7,BLITZ:4},4:{RUN:10,PASS:10,TACKLE:9,INTERCEPTION:5,BLOCK:9,BLITZ:5}};
const HAND={2:7,3:6,4:5}, ICON={RUN:'🏃',PASS:'🎯',TACKLE:'💥',INTERCEPTION:'🦅',BLOCK:'🛡️',BLITZ:'⚡'}, YARDS=[50,40,30,20,10];
const G={size:2,mode:'single',lang:'zh',players:[],deck:[],discard:[],currentTeam:'red',currentIndex:0,holderId:null,redProgress:0,blueProgress:0,redBalls:0,blueBalls:0,round:1,firstTeam:null,phase:'setup',activeTeam:null,pending:null,aiBusy:false,rps:{red:null,blue:null}};
window.G=G;
const T={zh:{rules:'玩法说明',reset:'重新设置',sub:'橄榄球比赛现场版 · 单人模式 / 多人本地操作',stadium:'真实美式橄榄球比赛现场视角',redEnd:'红队端区',blueEnd:'蓝队端区',drive:'4次成功 = TOUCHDOWN · 50为起点 · 第4次成功到10后自动冲入END ZONE',redPos:'红队推进位置',bluePos:'蓝队推进位置',quick:'快速换人',tip:'50是起点 · 第4次成功直接达阵',playHint:'单人模式：你只操作红队，蓝队由电脑自动操作。多人本地：双方轮流操作。',log:'对局记录',footer:'单人模式：红队由你操作，蓝队由电脑控制。<br>多人本地：红蓝双方轮流操作，换边时遮挡屏幕交接设备。',start:'开始游戏',size:'选择人数模式',sizeDesc:'2v2：每人7张 / 3v3：每人6张 / 4v4：每人5张',view:'选择操作模式',single:'单人模式',multi:'多人本地操作',viewDesc:'单人模式：你控制红队，蓝队由电脑控制。多人本地：双方轮流操作。',enter:'开始进入比赛现场',rulesTitle:'界面说明',close:'关闭',ready:'我已准备好，显示手牌',skillTitle:'QUARTERBACK 身份技能',useSkill:'使用技能（立即消耗）',skipSkill:'暂不使用',next:'下一个人',prev:'上一个人',mode:'模式',role:'身份',skill:'技能状态',team:'队伍',used:'已使用',available:'可用',none:'无主动技能',cards:'张',currentHand:'当前手牌',current:'当前',deck:'牌库',holder:'当前持球者',chooseHolder:'选择持球者',attack:'进攻时刻',defense:'防守时刻',block:'BLOCK反制',finalBlitz:'BLITZ最终反制',touchdownRun:'冲入端区',gameover:'比赛结束',noDefense:'不防守',noBlock:'不用 BLOCK',skipBlitz:'放弃 BLITZ',red:'红队',blue:'蓝队',player:'球员',turn:'操作',nextRound:'继续下一回合',gameOverBtn:'比赛结束',computer:'电脑回合',rps:'石头剪刀布'},en:{rules:'Rules',reset:'Reset',sub:'American Football Stadium Edition · Solo / Local Multiplayer',stadium:'Real American Football Stadium View',redEnd:'RED END ZONE',blueEnd:'BLUE END ZONE',drive:'4 successful plays = TOUCHDOWN · Start at 50 · 4th success reaches 10 then auto-runs into END ZONE',redPos:'Red Team Field Position',bluePos:'Blue Team Field Position',quick:'Quick Switch',tip:'50 is the start · 4th success scores',playHint:'Solo: you control Red Team only; Blue Team is controlled by the computer. Local Multiplayer: both teams take turns.',log:'Match Log',footer:'Solo: you control Red Team and the computer controls Blue Team.<br>Local Multiplayer: both teams take turns and the screen is covered during handoff.',start:'Start Game',size:'Choose Team Size',sizeDesc:'2v2: 7 cards each / 3v3: 6 cards each / 4v4: 5 cards each',view:'Choose Play Mode',single:'Solo',multi:'Local Multiplayer',viewDesc:'Solo: you control Red Team and Blue Team is AI-controlled. Local Multiplayer: both sides take turns.',enter:'Enter the Stadium',rulesTitle:'How This Version Works',close:'Close',ready:'Ready — Show Hand',skillTitle:'QUARTERBACK Skill',useSkill:'Use Skill (consumed immediately)',skipSkill:'Skip Skill',next:'Next Player',prev:'Previous Player',mode:'Mode',role:'Role',skill:'Skill',team:'Team',used:'Used',available:'Available',none:'No active skill',cards:'cards',currentHand:'Current Hand',current:'Current',deck:'Deck',holder:'Current Ball Carrier',chooseHolder:'Choose Ball Carrier',attack:'Offense',defense:'Defense',block:'BLOCK Response',finalBlitz:'Final BLITZ',touchdownRun:'Run to End Zone',gameover:'Game Over',noDefense:'No Defense',noBlock:'No BLOCK',skipBlitz:'Skip BLITZ',red:'Red Team',blue:'Blue Team',player:'Player',turn:'turn',nextRound:'Next Round',gameOverBtn:'Game Over',computer:'Computer Turn',rps:'Rock Paper Scissors'}};
const tx=k=>T[G.lang][k]||k, teamName=t=>t==='red'?tx('red'):tx('blue'), roleName=r=>r==='QB'?'QB':tx('player'), label=p=>G.lang==='zh'?`${teamName(p.team)}${p.num}号`:`${teamName(p.team)} #${p.num}`;
const desc=t=>({zh:{RUN:'持球推进',PASS:'传给队友',TACKLE:'阻止 RUN',INTERCEPTION:'抄截 PASS',BLOCK:'抵消防守',BLITZ:'强力突袭'},en:{RUN:'advance the ball',PASS:'pass to a teammate',TACKLE:'stop a RUN',INTERCEPTION:'intercept a PASS',BLOCK:'counter a defense',BLITZ:'aggressive pressure'}}[G.lang][t]);
const shuffle=a=>{for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const byId=id=>G.players.find(p=>p.id===id), teamPlayers=t=>G.players.filter(p=>p.team===t), currentPlayer=()=>G.players[G.currentIndex], holder=()=>byId(G.holderId), idx=id=>G.players.findIndex(p=>p.id===id), balls=n=>[0,1,2].map(i=>i<n?'🏈':'⚪').join(' ');
const progress=t=>t==='red'?G.redProgress:G.blueProgress, setProgress=(t,v)=>{if(t==='red')G.redProgress=v;else G.blueProgress=v}, yard=t=>YARDS[Math.min(4,Math.max(0,progress(t)))], driveX=t=>{let p=Math.min(4,Math.max(0,progress(t)));return t==='red'?[50,58,66,74,82][p]:[50,42,34,26,18][p]}, driveTeam=()=>holder()?.team||G.activeTeam||G.firstTeam||'red';
const hasOffense=p=>p&&(p.hand.includes('RUN')||p.hand.includes('PASS')), teamHasOffense=t=>teamPlayers(t).some(hasOffense);
function addLog(h){let d=document.createElement('div');d.className='logItem';d.innerHTML=h;$('log').prepend(d)}
function buildDeck(){let d=[];Object.entries(POOLS[G.size]).forEach(([t,n])=>{for(let i=0;i<n;i++)d.push(t)});return shuffle(d)}
function consume(p,t){let i=p.hand.indexOf(t);if(i<0)return false;p.hand.splice(i,1);G.discard.push(t);return true}
function updateStatic(){document.documentElement.lang=G.lang==='zh'?'zh-CN':'en';$('subtitleText').textContent=tx('sub');$('rulesBtn').textContent=tx('rules');$('restartBtn').textContent=tx('reset');$('langToggleBtn').textContent='中文 / EN';$('stadiumTitle').textContent=tx('stadium');$('leftEndzone').textContent=tx('redEnd');$('rightEndzone').textContent=tx('blueEnd');$('driveHint').textContent=tx('drive');$('redTeamTitle').textContent=tx('redPos');$('blueTeamTitle').textContent=tx('bluePos');$('playerSwitchLabel').textContent=tx('quick');$('ruleChip').textContent=tx('tip');$('playHint').textContent=tx('playHint');$('logTitle').textContent=tx('log');$('footerNote').innerHTML=tx('footer');$('setupTitle').textContent=tx('start');$('sizeTitle').textContent=tx('size');$('sizeDesc').textContent=tx('sizeDesc');$('viewTitle').textContent=tx('view');$('singleModeBtn').textContent=tx('single');$('multiModeBtn').textContent=tx('multi');$('viewDesc').textContent=tx('viewDesc');$('startBtn').textContent=tx('enter');$('rulesHeading').textContent=tx('rulesTitle');$('closeRulesBtn').textContent=tx('close');$('privacyConfirmBtn').textContent=tx('ready');$('skillHeading').textContent=tx('skillTitle');$('useSkillBtn').textContent=tx('useSkill');$('skipSkillBtn').textContent=tx('skipSkill');$('prevBtn').textContent=tx('prev');$('nextBtn').textContent=tx('next');}
function phaseText(){return ({rps:tx('rps'),chooseHolder:tx('chooseHolder'),attack:tx('attack'),skill:tx('skill'),defense:tx('defense'),block:tx('block'),blitzAfterBlock:tx('finalBlitz'),touchdownRun:tx('touchdownRun'),gameover:tx('gameover')})[G.phase]||''}
function createGame(){G.players=[];G.deck=buildDeck();G.discard=[];G.currentTeam='red';G.currentIndex=0;G.holderId=null;G.redProgress=G.blueProgress=G.redBalls=G.blueBalls=0;G.round=1;G.firstTeam=null;G.pending=null;G.aiBusy=false;G.rps={red:null,blue:null};for(let i=0;i<G.size;i++)G.players.push({id:`R${i+1}`,team:'red',num:i+1,role:'PLAYER',revealed:true,skillUsed:false,hand:[]});for(let i=0;i<G.size;i++)G.players.push({id:`B${i+1}`,team:'blue',num:i+1,role:'PLAYER',revealed:false,skillUsed:false,hand:[]});G.players[Math.floor(Math.random()*G.size)].role='QB';G.players[G.size+Math.floor(Math.random()*G.size)].role='QB';for(let r=0;r<HAND[G.size];r++)for(const p of G.players){let c=G.deck.pop();if(c)p.hand.push(c)}G.phase='rps';G.activeTeam=null;$('log').innerHTML='';addLog(G.lang==='zh'?`<b>开局：</b>${G.size}v${G.size}。先用石头剪刀布决定第一轮先攻方。`:`<b>Opening:</b> ${G.size}v${G.size}. Rock-Paper-Scissors decides who attacks first.`)}
function collectRedeal(){let pool=[...G.deck,...G.discard];for(const p of G.players){pool.push(...p.hand);p.hand=[]}G.deck=shuffle(pool);G.discard=[];for(let r=0;r<HAND[G.size];r++)for(const p of G.players){let c=G.deck.pop();if(c)p.hand.push(c)}}
function renderField(){const root=$('fieldPlayers');root.innerHTML='';const off=driveTeam(),def=off==='red'?'blue':'red',line=driveX(off),dir=off==='red'?1:-1,ys={2:[35,62],3:[24,50,76],4:[18,38,58,78]}[G.size];$('scrimmageLine').style.left=line+'%';$('scrimmageBadge').style.left=line+'%';$('scrimmageBadge').textContent=`${teamName(off)} · BALL ON ${yard(off)}`;for(const p of teamPlayers(off)){let i=p.num-1,d=document.createElement('div'),ball=p.id===G.holderId,x=ball?line:line-dir*(5+(i%2)*2),role=(p.team===G.currentTeam||p.revealed)?roleName(p.role):'?';x=Math.max(10,Math.min(90,x));d.id='fieldPlayer_'+p.id;d.className=`player ${p.team} ${p.id===currentPlayer()?.id?'active':''} ${ball?'ball':''}`;d.style.left=`calc(${x}% - 36px)`;d.style.top=`calc(${ys[i]}% - 36px)`;d.innerHTML=`${ball?'<div class="ballIcon">🏈</div>':''}<div class="num">${p.num}</div><div class="role">${role}</div>`;d.onclick=()=>switchTo(p);root.appendChild(d)}for(const p of teamPlayers(def)){let i=p.num-1,d=document.createElement('div'),ball=p.id===G.holderId,x=ball?driveX(p.team):line+dir*(6+(i%2)*2),role=(p.team===G.currentTeam||p.revealed)?roleName(p.role):'?';x=Math.max(10,Math.min(90,x));d.id='fieldPlayer_'+p.id;d.className=`player ${p.team} ${p.id===currentPlayer()?.id?'active':''} ${ball?'ball':''}`;d.style.left=`calc(${x}% - 36px)`;d.style.top=`calc(${ys[i]}% - 36px)`;d.innerHTML=`${ball?'<div class="ballIcon">🏈</div>':''}<div class="num">${p.num}</div><div class="role">${role}</div>`;d.onclick=()=>switchTo(p);root.appendChild(d)}}
function renderBottom(){let h=holder();$('redProg').textContent=yard('red')+' YD';$('blueProg').textContent=yard('blue')+' YD';$('redFill').style.width=G.redProgress*25+'%';$('blueFill').style.width=G.blueProgress*25+'%';$('redBalls').textContent=balls(G.redBalls);$('blueBalls').textContent=balls(G.blueBalls);$('holderText').textContent=`🏈 ${tx('holder')}: ${h?label(h):'--'}`;$('roundText').textContent=G.phase==='rps'?(G.lang==='zh'?'开局：石头剪刀布决定第一轮先攻':'Opening: Rock-Paper-Scissors decides first offense'):(G.lang==='zh'?`第 ${G.round} 回合 · ${teamName(G.firstTeam)}先攻 · ${phaseText()} · ${teamName(driveTeam())}在${yard(driveTeam())}码`:`Round ${G.round} · ${teamName(G.firstTeam)} attacks first · ${phaseText()} · ${teamName(driveTeam())} at ${yard(driveTeam())}`)}
function humanTurn(){return G.mode==='multi'||G.currentTeam==='red'}
function allowed(p,t){if(G.phase==='rps')return false;if(!humanTurn())return false;if(!p||p.team!==G.currentTeam)return false;if(G.phase==='attack'&&G.activeTeam===p.team&&p.id===G.holderId)return t==='RUN'||t==='PASS';if(G.phase==='defense'&&G.activeTeam===p.team)return G.pending.action==='RUN'?['TACKLE','BLITZ'].includes(t):['INTERCEPTION','BLITZ'].includes(t);if(G.phase==='block'&&G.activeTeam===p.team)return t==='BLOCK';if(G.phase==='blitzAfterBlock'&&G.activeTeam===p.team)return t==='BLITZ';return false}
/* rest of original file retained below */
