(()=>{
const $=id=>document.getElementById(id);
const POOLS={2:{RUN:6,PASS:6,TACKLE:5,INTERCEPTION:3,BLOCK:5,BLITZ:3},3:{RUN:8,PASS:8,TACKLE:7,INTERCEPTION:4,BLOCK:7,BLITZ:4},4:{RUN:10,PASS:10,TACKLE:9,INTERCEPTION:5,BLOCK:9,BLITZ:5}};
const HAND={2:7,3:6,4:5}, ICON={RUN:'🏃',PASS:'🎯',TACKLE:'💥',INTERCEPTION:'🦅',BLOCK:'🛡️',BLITZ:'⚡'}, YARDS=[50,40,30,20,10];
const G={size:2,mode:'single',lang:'zh',players:[],deck:[],discard:[],currentTeam:'red',currentIndex:0,holderId:null,redProgress:0,blueProgress:0,redBalls:0,blueBalls:0,round:1,firstTeam:null,phase:'setup',activeTeam:null,pending:null,aiBusy:false,rps:{red:null,blue:null}};
const T={zh:{rules:'玩法说明',reset:'重新设置',sub:'橄榄球比赛现场版 · 单人模式 / 多人本地操作',stadium:'真实美式橄榄球比赛现场视角',redEnd:'红队端区',blueEnd:'蓝队端区',drive:'4次成功 = TOUCHDOWN · 50为起点 · 第4次成功到10后自动冲入END ZONE',redPos:'红队推进位置',bluePos:'蓝队推进位置',quick:'快速换人',tip:'50是起点 · 第4次成功直接达阵',playHint:'单人模式：你只操作红队，蓝队由电脑自动操作。多人本地：双方轮流操作。',log:'对局记录',footer:'单人模式：红队由你操作，蓝队由电脑控制。<br>多人本地：红蓝双方轮流操作，换边时遮挡屏幕交接设备。',start:'开始游戏',size:'选择人数模式',sizeDesc:'2v2：每人7张 / 3v3：每人6张 / 4v4：每人5张',view:'选择操作模式',single:'单人模式',multi:'多人本地操作',viewDesc:'单人模式：你控制红队，蓝队由电脑控制。多人本地：双方轮流操作。',enter:'开始进入比赛现场',rulesTitle:'界面说明',close:'关闭',ready:'我已准备好，显示手牌',skillTitle:'QUARTERBACK 身份技能',useSkill:'使用技能（立即消耗）',skipSkill:'暂不使用',next:'下一个人',prev:'上一个人',mode:'模式',role:'身份',skill:'技能状态',team:'队伍',used:'已使用',available:'可用',none:'无主动技能',cards:'张',currentHand:'当前手牌',current:'当前',deck:'牌库',holder:'当前持球者',chooseHolder:'选择持球者',attack:'进攻时刻',defense:'防守时刻',block:'BLOCK反制',finalBlitz:'BLITZ最终反制',touchdownRun:'冲入端区',gameover:'比赛结束',noDefense:'不防守',noBlock:'不用 BLOCK',skipBlitz:'放弃 BLITZ',red:'红队',blue:'蓝队',player:'球员',turn:'操作',nextRound:'继续下一回合',gameOverBtn:'比赛结束',computer:'电脑回合',rps:'石头剪刀布'},en:{rules:'Rules',reset:'Reset',sub:'American Football Stadium Edition · Solo / Local Multiplayer',stadium:'Real American Football Stadium View',redEnd:'RED END ZONE',blueEnd:'BLUE END ZONE',drive:'4 successful plays = TOUCHDOWN · Start at 50 · 4th success reaches 10 then auto-runs into END ZONE',redPos:'Red Team Field Position',bluePos:'Blue Team Field Position',quick:'Quick Switch',tip:'50 is the start · 4th success scores',playHint:'Solo: you control Red Team only; Blue Team is controlled by the computer. Local Multiplayer: both teams take turns.',log:'Match Log',footer:'Solo: you control Red Team and the computer controls Blue Team.<br>Local Multiplayer: both teams take turns and the screen is covered during handoff.',start:'Start Game',size:'Choose Team Size',sizeDesc:'2v2: 7 cards each / 3v3: 6 cards each / 4v4: 5 cards each',view:'Choose Play Mode',single:'Solo',multi:'Local Multiplayer',viewDesc:'Solo: you control Red Team and Blue Team is AI-controlled. Local Multiplayer: both sides take turns.',enter:'Enter the Stadium',rulesTitle:'How This Version Works',close:'Close',ready:'Ready — Show Hand',skillTitle:'QUARTERBACK Skill',useSkill:'Use Skill (consumed immediately)',skipSkill:'Skip Skill',next:'Next Player',prev:'Previous Player',mode:'Mode',role:'Role',skill:'Skill',team:'Team',used:'Used',available:'Available',none:'No active skill',cards:'cards',currentHand:'Current Hand',current:'Current',deck:'Deck',holder:'Current Ball Carrier',chooseHolder:'Choose Ball Carrier',attack:'Offense',defense:'Defense',block:'BLOCK Response',finalBlitz:'Final BLITZ',touchdownRun:'Run to End Zone',gameover:'Game Over',noDefense:'No Defense',noBlock:'No BLOCK',skipBlitz:'Skip BLITZ',red:'Red Team',blue:'Blue Team',player:'Player',turn:'turn',nextRound:'Next Round',gameOverBtn:'Game Over',computer:'Computer Turn',rps:'Rock Paper Scissors'}};
const tx=k=>T[G.lang][k]||k, teamName=t=>t==='red'?tx('red'):tx('blue'), roleName=r=>r==='QB'?'QB':tx('player'), label=p=>G.lang==='zh'?`${teamName(p.team)}${p.num}号`:`${teamName(p.team)} #${p.num}`;
const desc=t=>({zh:{RUN:'持球推进',PASS:'传给队友',TACKLE:'阻止 RUN',INTERCEPTION:'抄截 PASS',BLOCK:'抵消防守',BLITZ:'强力突袭'},en:{RUN:'advance the ball',PASS:'pass to a teammate',TACKLE:'stop a RUN',INTERCEPTION:'intercept a PASS',BLOCK:'counter a defense',BLITZ:'aggressive pressure'}}[G.lang][t]);
const shuffle=a=>{for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
const byId=id=>G.players.find(p=>p.id===id), teamPlayers=t=>G.players.filter(p=>p.team===t), currentPlayer=()=>G.players[G.currentIndex], holder=()=>byId(G.holderId), idx=id=>G.players.findIndex(p=>p.id===id), balls=n=>[0,1,2].map(i=>i<n?'🏈':'⚪').join(' ');
const progress=t=>t==='red'?G.redProgress:G.blueProgress, setProgress=(t,v)=>{if(t==='red')G.redProgress=v;else G.blueProgress=v}, yard=t=>YARDS[Math.min(4,Math.max(0,progress(t)))], driveX=t=>{let p=Math.min(4,Math.max(0,progress(t)));return t==='red'?[50,58,66,74,82][p]:[50,42,34,26,18][p]}, driveTeam=()=>holder()?.team||G.activeTeam||G.firstTeam||'red';
const hasOffense=p=>p&&(p.hand.includes('RUN')||p.hand.includes('PASS')), teamHasOffense=t=>teamPlayers(t).some(hasOffense);
function addLog(h){let d=document.createElement('div');d.className='logItem';d.innerHTML=h;$('log').prepend(d)}
function buildDeck(){let d=[];Object.entries(POOLS[G.size]).forEach(([t,n])=>{for(let i=0;i<n;i++)d.push(t)});return shuffle(d)}
function consume(p,t){let i=p.hand.indexOf(t);if(i<0)return false;p.hand.splice(i,1);G.discard.push(t);return true}
function updateStatic(){document.documentElement.lang=G.lang==='zh'?'zh-CN':'en';$('subtitleText').textContent=tx('sub');$('rulesBtn').textContent=tx('rules');$('restartBtn').textContent=tx('reset');$('langToggleBtn').textContent='中文 / EN';$('stadiumTitle').textContent=tx('stadium');$('leftEndzone').textContent=tx('redEnd');$('rightEndzone').textContent=tx('blueEnd');$('driveHint').textContent=tx('drive');$('redTeamTitle').textContent=tx('redPos');$('blueTeamTitle').textContent=tx('bluePos');$('playerSwitchLabel').textContent=tx('quick');$('ruleChip').textContent=tx('tip');$('playHint').textContent=tx('playHint');$('logTitle').textContent=tx('log');$('footerNote').innerHTML=tx('footer');$('setupTitle').textContent=tx('start');$('sizeTitle').textContent=tx('size');$('sizeDesc').textContent=tx('sizeDesc');$('viewTitle').textContent=tx('view');$('singleModeBtn').textContent=tx('single');$('multiModeBtn').textContent=tx('multi');$('viewDesc').textContent=tx('viewDesc');$('startBtn').textContent=tx('enter');$('rulesHeading').textContent=tx('rulesTitle');$('closeRulesBtn').textContent=tx('close');$('privacyConfirmBtn').textContent=tx('ready');$('skillHeading').textContent=tx('skillTitle');$('useSkillBtn').textContent=tx('useSkill');$('skipSkillBtn').textContent=tx('skipSkill');$('prevBtn').textContent=tx('prev');$('nextBtn').textContent=tx('next');}
function phaseText(){return ({rps:tx('rps'),chooseHolder:tx('chooseHolder'),attack:tx('attack'),skill:tx('skill'),defense:tx('defense'),block:tx('block'),blitzAfterBlock:tx('finalBlitz'),touchdownRun:tx('touchdownRun'),gameover:tx('gameover')})[G.phase]||''}
function createGame(){G.players=[];G.deck=buildDeck();G.discard=[];G.currentTeam='red';G.currentIndex=0;G.holderId=null;G.redProgress=G.blueProgress=G.redBalls=G.blueBalls=0;G.round=1;G.firstTeam=null;G.pending=null;G.aiBusy=false;G.rps={red:null,blue:null};for(let i=0;i<G.size;i++)G.players.push({id:`R${i+1}`,team:'red',num:i+1,role:'PLAYER',revealed:true,skillUsed:false,hand:[]});for(let i=0;i<G.size;i++)G.players.push({id:`B${i+1}`,team:'blue',num:i+1,role:'PLAYER',revealed:false,skillUsed:false,hand:[]});G.players[Math.floor(Math.random()*G.size)].role='QB';G.players[G.size+Math.floor(Math.random()*G.size)].role='QB';for(let r=0;r<HAND[G.size];r++)for(const p of G.players){let c=G.deck.pop();if(c)p.hand.push(c)}G.phase='rps';G.activeTeam=null;$('log').innerHTML='';addLog(G.lang==='zh'?`<b>开局：</b>${G.size}v${G.size}。先用石头剪刀布决定第一轮先攻方。`:`<b>Opening:</b> ${G.size}v${G.size}. Rock-Paper-Scissors decides who attacks first.`)}
function collectRedeal(){let pool=[...G.deck,...G.discard];for(const p of G.players){pool.push(...p.hand);p.hand=[]}G.deck=shuffle(pool);G.discard=[];for(let r=0;r<HAND[G.size];r++)for(const p of G.players){let c=G.deck.pop();if(c)p.hand.push(c)}}
function renderField(){const root=$('fieldPlayers');root.innerHTML='';const off=driveTeam(),def=off==='red'?'blue':'red',line=driveX(off),dir=off==='red'?1:-1,ys={2:[35,62],3:[24,50,76],4:[18,38,58,78]}[G.size];$('scrimmageLine').style.left=line+'%';$('scrimmageBadge').style.left=line+'%';$('scrimmageBadge').textContent=`${teamName(off)} · BALL ON ${yard(off)}`;for(const p of teamPlayers(off)){let i=p.num-1,d=document.createElement('div'),ball=p.id===G.holderId,x=ball?line:line-dir*(5+(i%2)*2),role=(p.team===G.currentTeam||p.revealed)?roleName(p.role):'?';x=Math.max(10,Math.min(90,x));d.id='fieldPlayer_'+p.id;d.className=`player ${p.team} ${p.id===currentPlayer()?.id?'active':''} ${ball?'ball':''}`;d.style.left=`calc(${x}% - 36px)`;d.style.top=`calc(${ys[i]}% - 36px)`;d.innerHTML=`${ball?'<div class="ballIcon">🏈</div>':''}<div class="num">${p.num}</div><div class="role">${role}</div>`;d.onclick=()=>switchTo(p);root.appendChild(d)}for(const p of teamPlayers(def)){let i=p.num-1,d=document.createElement('div'),ball=p.id===G.holderId,x=ball?driveX(p.team):line+dir*(6+(i%2)*2),role=(p.team===G.currentTeam||p.revealed)?roleName(p.role):'?';x=Math.max(10,Math.min(90,x));d.id='fieldPlayer_'+p.id;d.className=`player ${p.team} ${p.id===currentPlayer()?.id?'active':''} ${ball?'ball':''}`;d.style.left=`calc(${x}% - 36px)`;d.style.top=`calc(${ys[i]}% - 36px)`;d.innerHTML=`${ball?'<div class="ballIcon">🏈</div>':''}<div class="num">${p.num}</div><div class="role">${role}</div>`;d.onclick=()=>switchTo(p);root.appendChild(d)}}
function renderBottom(){let h=holder();$('redProg').textContent=yard('red')+' YD';$('blueProg').textContent=yard('blue')+' YD';$('redFill').style.width=G.redProgress*25+'%';$('blueFill').style.width=G.blueProgress*25+'%';$('redBalls').textContent=balls(G.redBalls);$('blueBalls').textContent=balls(G.blueBalls);$('holderText').textContent=`🏈 ${tx('holder')}: ${h?label(h):'--'}`;$('roundText').textContent=G.phase==='rps'?(G.lang==='zh'?'开局：石头剪刀布决定第一轮先攻':'Opening: Rock-Paper-Scissors decides first offense'):(G.lang==='zh'?`第 ${G.round} 回合 · ${teamName(G.firstTeam)}先攻 · ${phaseText()} · ${teamName(driveTeam())}在${yard(driveTeam())}码`:`Round ${G.round} · ${teamName(G.firstTeam)} attacks first · ${phaseText()} · ${teamName(driveTeam())} at ${yard(driveTeam())}`)}
function humanTurn(){return G.mode==='multi'||G.currentTeam==='red'}
function allowed(p,t){if(G.phase==='rps')return false;if(!humanTurn())return false;if(!p||p.team!==G.currentTeam)return false;if(G.phase==='attack'&&G.activeTeam===p.team&&p.id===G.holderId)return t==='RUN'||t==='PASS';if(G.phase==='defense'&&G.activeTeam===p.team)return G.pending.action==='RUN'?['TACKLE','BLITZ'].includes(t):['INTERCEPTION','BLITZ'].includes(t);if(G.phase==='block'&&G.activeTeam===p.team)return t==='BLOCK';if(G.phase==='blitzAfterBlock'&&G.activeTeam===p.team)return t==='BLITZ';return false}
function renderHand(){let p=currentPlayer();if(!p)return;$('currentPlayerText').textContent=G.mode==='single'&&G.currentTeam==='blue'?tx('computer'):`${tx('currentHand')}: ${label(p)}`;$('viewModeChip').textContent=`${tx('mode')}: ${G.mode==='multi'?tx('multi'):tx('single')}`;$('roleChip').textContent=`${tx('role')}: ${G.mode==='single'&&G.currentTeam==='blue'?'?':roleName(p.role)}`;$('skillChip').textContent=`${tx('skill')}: ${G.mode==='single'&&G.currentTeam==='blue'?'?':(p.role==='QB'?(p.skillUsed?tx('used'):tx('available')):tx('none'))}`;$('teamChip').textContent=`${tx('team')}: ${teamName(p.team)}`;let root=$('hand');root.innerHTML='';if(G.phase==='rps'){root.innerHTML=`<div style="padding:34px;text-align:center;font-size:18px;font-weight:900">✊ ✌️ 🖐️<br><span style="font-size:12px;font-weight:400;opacity:.7">${G.lang==='zh'?'先决定第一轮先攻方':'Decide who attacks first'}</span></div>`;return}if(G.mode==='single'&&G.currentTeam==='blue'){root.innerHTML=`<div style="padding:34px;text-align:center;font-size:18px;font-weight:900">🤖 ${tx('computer')}<br><span style="font-size:12px;font-weight:400;opacity:.7">${G.lang==='zh'?'蓝队正在自动操作…':'Blue Team is playing automatically…'}</span></div>`;return}let total=p.hand.length;p.hand.forEach((t,i)=>{let c=document.createElement('div'),mid=(total-1)/2,rot=(i-mid)*5,lift=Math.abs(i-mid)*2.5;c.className=`card ${t.toLowerCase()} ${allowed(p,t)?'':'disabled'}`;c.style.setProperty('--rot',rot+'deg');c.style.transform=`rotate(${rot}deg) translateY(${lift}px)`;c.style.zIndex=10+i;c.innerHTML=`<div><div class="icon">${ICON[t]}</div><div class="name">${t}</div></div><div class="desc">${desc(t)}</div>`;if(allowed(p,t))c.onclick=()=>playCard(p,t);root.appendChild(c)})}
function renderSwitch(){let root=$('switchList');root.innerHTML='';if(G.phase==='rps')return;if(G.mode==='single'&&G.currentTeam==='blue'){root.innerHTML=`<div class="switchBtn active"><b>🤖 ${tx('computer')}</b><small>${teamName('blue')}</small></div>`;return}for(const p of teamPlayers(G.currentTeam)){let b=document.createElement('button'),i=idx(p.id);b.className=`switchBtn ${i===G.currentIndex?'active':''}`;b.innerHTML=`<b>${label(p)}</b><small>${roleName(p.role)} · ${p.hand.length} ${tx('cards')}</small>`;b.onclick=()=>{G.currentIndex=i;renderAll()};root.appendChild(b)}}
function renderTop(){$('modeText').textContent=`${G.size}v${G.size} · ${G.mode==='multi'?tx('multi'):tx('single')} · ${tx('drive')}`;$('turnTag').textContent=`${tx('current')}: ${G.phase==='rps'?tx('rps'):(G.mode==='single'&&G.currentTeam==='blue'?tx('computer'):teamName(G.currentTeam))} · ${phaseText()}`;$('deckTag').textContent=`${tx('deck')}: ${G.deck.length}`;$('activeModeTag').textContent=G.phase==='rps'?`✊ ${tx('rps')}`:(G.mode==='single'&&G.currentTeam==='blue'?`🤖 ${tx('computer')}`:`${teamName(G.activeTeam||G.currentTeam)} ${tx('turn')}`)}
function showActions(title,arr){$('actionTitle').textContent=title;let r=$('actionButtons');r.innerHTML='';$('actionPanel').classList.remove('hidden');for(const x of arr){let b=document.createElement('button');b.className='btn '+(x.primary?'primary':'');b.textContent=x.label;b.onclick=x.fn;r.appendChild(b)}} function hideActions(){$('actionPanel').classList.add('hidden');$('actionButtons').innerHTML=''}
function renderActions(){hideActions();if(G.phase==='rps')return;if(!humanTurn())return;if(G.phase==='chooseHolder'&&G.activeTeam===G.currentTeam){let ps=teamPlayers(G.activeTeam).filter(hasOffense);showActions(tx('chooseHolder'),ps.map((p,i)=>({label:`🏈 ${label(p)}`,primary:i===0,fn:()=>chooseHolder(p)})))}else if(G.phase==='defense'&&G.activeTeam===G.currentTeam)showActions(G.lang==='zh'?`对方发动 ${G.pending.action}`:`Opponent used ${G.pending.action}`,[{label:tx('noDefense'),fn:resolveAttackSuccess}]);else if(G.phase==='block'&&G.activeTeam===G.currentTeam)showActions(G.lang==='zh'?`对方使用 ${G.pending.defense}`:`Opponent played ${G.pending.defense}`,[{label:tx('noBlock'),fn:resolveNormalDefense}]);else if(G.phase==='blitzAfterBlock'&&G.activeTeam===G.currentTeam)showActions(G.lang==='zh'?'对方已经使用 BLOCK':'Opponent used BLOCK',[{label:tx('skipBlitz'),fn:resolveAttackSuccess}])}
function renderAll(){if(!G.players.length)return;renderField();renderBottom();renderHand();renderSwitch();renderTop();renderActions();scheduleAI()}
function firstIndex(t){let p=teamPlayers(t)[0];return p?idx(p.id):0}
function handoff(team,title,text,after){G.currentTeam=team;G.currentIndex=firstIndex(team);if(G.mode==='multi'){$('privacyTitle').textContent=title||teamName(team);$('privacyText').textContent=text||'';$('privacyModal').classList.add('show');$('privacyConfirmBtn').onclick=()=>{$('privacyModal').classList.remove('show');renderAll();if(after)after()}}else{renderAll();if(after)after()}}
function switchTo(p){if(G.phase==='rps')return;if(G.mode==='single'&&p.team==='blue')return;if(p.team!==G.currentTeam)return;G.currentIndex=idx(p.id);renderAll()} function cycle(dir){if(G.phase==='rps')return;if(G.mode==='single'&&G.currentTeam==='blue')return;let a=teamPlayers(G.currentTeam).map(p=>idx(p.id)),i=a.indexOf(G.currentIndex);if(i<0)i=0;G.currentIndex=a[(i+dir+a.length)%a.length];renderAll()}
function chooseHolder(p){G.holderId=p.id;G.phase='attack';G.activeTeam=p.team;G.currentIndex=idx(p.id);addLog(`<b>${G.lang==='zh'?'持球':'Ball Carrier'}：</b>${label(p)}`);renderAll()}
function playCard(p,t){if(G.phase==='attack'){if(!consume(p,t))return;if(t==='PASS'){let targets=teamPlayers(p.team).filter(x=>x.id!==p.id);showActions(G.lang==='zh'?'PASS 给哪名队友？':'Choose a PASS target',targets.map((x,i)=>({label:label(x),primary:i===0,fn:()=>passTarget(p,x)})))}else{G.pending={team:p.team,attacker:p.id,action:'RUN',target:p.id,skillArmed:false};addLog(`<b>${label(p)}:</b> RUN`);goDefense()}}else if(G.phase==='defense'){if(!consume(p,t))return;G.pending.defender=p.id;G.pending.defense=t;addLog(`<b>${label(p)}:</b> ${t}`);if(t==='BLITZ'){resolveFail(blitzReason());return}let atk=G.pending.team;G.phase='block';G.activeTeam=atk;handoff(atk,'','')}else if(G.phase==='block'){if(t!=='BLOCK'||!consume(p,t))return;addLog(`<b>${label(p)}:</b> BLOCK`);let def=p.team==='red'?'blue':'red';G.phase='blitzAfterBlock';G.activeTeam=def;handoff(def,'','')}else if(G.phase==='blitzAfterBlock'){if(t!=='BLITZ'||!consume(p,t))return;addLog(`<b>${label(p)}:</b> BLITZ`);resolveFail(blitzReason())}}
function passTarget(p,target){hideActions();G.pending={team:p.team,attacker:p.id,action:'PASS',target:target.id,skillArmed:false};addLog(`<b>${label(p)}:</b> PASS → ${label(target)}`);if(p.role==='QB'&&!p.skillUsed){G.phase='skill';G.activeTeam=p.team;if(G.mode==='single'&&p.team==='blue'){scheduleAI();return}$('skillText').textContent=G.lang==='zh'?`${label(p)} 是否使用QB技能？使用后立即消耗。`:`Use ${label(p)}'s QB skill? It is consumed immediately.`;$('skillModal').classList.add('show');renderAll()}else goDefense()}
function skillDecision(use){let a=byId(G.pending.attacker);G.pending.skillArmed=use;if(use)a.skillUsed=true;addLog(`<b>QB:</b> ${use?(G.lang==='zh'?'使用技能':'Skill used'):(G.lang==='zh'?'不使用技能':'Skill skipped')}`);$('skillModal').classList.remove('show');goDefense()}
function goDefense(){let def=G.pending.team==='red'?'blue':'red';G.phase='defense';G.activeTeam=def;handoff(def,'','')}
function blitzReason(){let a=byId(G.pending.attacker);return a.role==='QB'&&a.revealed?(G.lang==='zh'?'SACK：BLITZ 擒杀已暴露 QB。':'SACK: BLITZ brings down the revealed QB.'):(G.lang==='zh'?'BLITZ 终止本次进攻。':'BLITZ stops the play.')}
function resolveNormalDefense(){if(G.pending.defense==='TACKLE')resolveFail(G.lang==='zh'?'TACKLE 阻止 RUN。':'TACKLE stops the RUN.');else{let d=byId(G.pending.defender);G.holderId=d.id;G.pending=null;G.phase='attack';G.activeTeam=d.team;addLog(`<b>INTERCEPTION:</b> ${label(d)}`);handoff(d.team,'','',()=>{G.currentIndex=idx(d.id);renderAll();afterPlay()})}}
function resolveAttackSuccess(){let x=G.pending,a=byId(x.attacker),gain=1;if(x.action==='PASS'){if(a.role==='QB'&&!a.revealed)a.revealed=true;if(x.skillArmed)gain=2;G.holderId=x.target}else G.holderId=a.id;let before=progress(a.team),after=Math.min(4,before+gain);setProgress(a.team,after);let from=YARDS[before],to=YARDS[after];addLog(G.lang==='zh'?`<b>进攻成功：</b>${teamName(a.team)} ${from} → ${to}`:`<b>Successful Play:</b> ${teamName(a.team)} ${from} → ${to}`);G.pending=null;G.phase=after>=4?'touchdownRun':'attack';G.activeTeam=a.team;renderAll();if(after>=4){setTimeout(()=>touchdown(a.team),420);return}handoff(a.team,'','',()=>{G.currentIndex=idx(G.holderId);renderAll();afterPlay()})}
function resolveFail(reason){let x=G.pending,a=byId(x.attacker);addLog(`<b>${G.lang==='zh'?'进攻失败':'Failed Play'}:</b> ${reason}`);G.holderId=a.id;G.pending=null;G.phase='attack';G.activeTeam=a.team;handoff(a.team,'','',()=>{G.currentIndex=idx(a.id);renderAll();afterPlay()})}
function afterPlay(){if(hasOffense(holder()))return;let from=holder()?.team||G.activeTeam,other=from==='red'?'blue':'red';if(!teamHasOffense(from)&&!teamHasOffense(other)){endRound();return}if(teamHasOffense(other)){G.holderId=null;G.phase='chooseHolder';G.activeTeam=other;handoff(other,'','');return}if(teamHasOffense(from)){G.holderId=null;G.phase='chooseHolder';G.activeTeam=from;handoff(from,'','')}}
function touchdown(team){let runner=holder();G.phase='touchdownRun';G.activeTeam=team;renderAll();let el=runner?$('fieldPlayer_'+runner.id):null;if(el){let end=team==='red'?91:9;requestAnimationFrame(()=>{el.classList.add('tdRunner');el.style.left=`calc(${end}% - 36px)`})}setTimeout(()=>{if(team==='red')G.redBalls++;else G.blueBalls++;$('touchdownTeam').textContent=G.lang==='zh'?`${teamName(team)} · 达阵成功！`:`${teamName(team)} · TOUCHDOWN!`;$('touchdownRoute').innerHTML='50 → 40 → 30 → 20 → 10 → <b>END ZONE</b>';$('touchdownModal').classList.add('show');renderBottom();let won=(team==='red'?G.redBalls:G.blueBalls)>=3;$('touchdownContinueBtn').textContent=won?tx('gameOverBtn'):tx('nextRound');if(G.mode==='single'&&team==='blue'){setTimeout(()=>$('touchdownContinueBtn').click(),1200)}$('touchdownContinueBtn').onclick=()=>{$('touchdownModal').classList.remove('show');setProgress(team,0);if(won){G.phase='gameover';G.activeTeam=null;renderAll();return}endRound()}},980)}
function beginRound(team){G.firstTeam=team;G.holderId=null;G.pending=null;G.phase='chooseHolder';G.activeTeam=team;handoff(team,G.lang==='zh'?`${teamName(team)}先攻`:`${teamName(team)} attacks first`,G.lang==='zh'?'请选择持球者。':'Choose a ball carrier.')}
function endRound(){collectRedeal();G.round++;G.firstTeam=G.firstTeam==='red'?'blue':'red';addLog(G.lang==='zh'?`<b>新回合：</b>重新发牌，第${G.round}回合改由${teamName(G.firstTeam)}先攻。`:`<b>New Round:</b> cards are redealt; ${teamName(G.firstTeam)} attacks first in Round ${G.round}.`);beginRound(G.firstTeam)}
function aiPickHolder(){let ps=teamPlayers('blue').filter(hasOffense);if(!ps.length){afterPlay();return}chooseHolder(ps[Math.floor(Math.random()*ps.length)])}
function aiAttack(){let p=holder();if(!p||p.team!=='blue'){aiPickHolder();return}let opts=p.hand.filter(x=>x==='RUN'||x==='PASS');if(!opts.length){afterPlay();return}let t=opts.includes('PASS')&&Math.random()<.55?'PASS':'RUN';if(!consume(p,t))return;if(t==='PASS'){let targets=teamPlayers('blue').filter(x=>x.id!==p.id);passTarget(p,targets[Math.floor(Math.random()*targets.length)])}else{G.pending={team:'blue',attacker:p.id,action:'RUN',target:p.id,skillArmed:false};addLog(`<b>${label(p)}:</b> RUN`);goDefense()}}
function aiDefense(){let attack=G.pending?.action;let choices=[];for(const p of teamPlayers('blue'))for(const c of p.hand){if(attack==='RUN'&&(c==='TACKLE'||c==='BLITZ'))choices.push([p,c]);if(attack==='PASS'&&(c==='INTERCEPTION'||c==='BLITZ'))choices.push([p,c])}if(!choices.length||Math.random()<.25){resolveAttackSuccess();return}let [p,c]=choices[Math.floor(Math.random()*choices.length)];G.currentIndex=idx(p.id);consume(p,c);G.pending.defender=p.id;G.pending.defense=c;addLog(`<b>${label(p)}:</b> ${c}`);if(c==='BLITZ'){resolveFail(blitzReason());return}G.phase='block';G.activeTeam='red';handoff('red','','')}
function aiBlock(){let p=teamPlayers('blue').find(x=>x.hand.includes('BLOCK'));if(p&&Math.random()<.65){G.currentIndex=idx(p.id);consume(p,'BLOCK');addLog(`<b>${label(p)}:</b> BLOCK`);G.phase='blitzAfterBlock';G.activeTeam='red';handoff('red','','')}else resolveNormalDefense()}
function aiFinalBlitz(){let p=teamPlayers('blue').find(x=>x.hand.includes('BLITZ'));if(p&&Math.random()<.55){G.currentIndex=idx(p.id);consume(p,'BLITZ');addLog(`<b>${label(p)}:</b> BLITZ`);resolveFail(blitzReason())}else resolveAttackSuccess()}
function aiSkill(){let a=byId(G.pending.attacker),use=Math.random()<.7;G.pending.skillArmed=use;if(use)a.skillUsed=true;addLog(`<b>QB:</b> ${use?(G.lang==='zh'?'电脑使用技能':'Computer uses skill'):(G.lang==='zh'?'电脑不使用技能':'Computer skips skill')}`);goDefense()}
function scheduleAI(){if(G.mode!=='single'||G.currentTeam!=='blue'||G.aiBusy||G.phase==='gameover'||G.phase==='rps')return;G.aiBusy=true;setTimeout(()=>{G.aiBusy=false;if(G.mode!=='single'||G.currentTeam!=='blue')return;if(G.phase==='chooseHolder')aiPickHolder();else if(G.phase==='attack')aiAttack();else if(G.phase==='defense')aiDefense();else if(G.phase==='block')aiBlock();else if(G.phase==='blitzAfterBlock')aiFinalBlitz();else if(G.phase==='skill')aiSkill()},700)}
function rpsWinner(a,b){if(a===b)return null;return (a==='rock'&&b==='scissors')||(a==='scissors'&&b==='paper')||(a==='paper'&&b==='rock')?'red':'blue'}
function rpsName(x){const z={rock:'✊ 石头',paper:'🖐️ 布',scissors:'✌️ 剪刀'},e={rock:'✊ Rock',paper:'🖐️ Paper',scissors:'✌️ Scissors'};return (G.lang==='zh'?z:e)[x]}
function buildRpsModal(){if($('rpsModal'))return;let m=document.createElement('div');m.className='modal';m.id='rpsModal';m.innerHTML=`<div class="modalBox" style="max-width:560px;text-align:center"><h2 id="rpsTitle"></h2><div id="rpsText" style="line-height:1.7;color:#dbe5de;margin:10px 0 16px"></div><div id="rpsButtons" style="display:flex;gap:10px;justify-content:center;flex-wrap:wrap"><button class="btn primary" data-rps="rock">✊</button><button class="btn primary" data-rps="paper">🖐️</button><button class="btn primary" data-rps="scissors">✌️</button></div></div>`;document.body.appendChild(m);m.querySelectorAll('[data-rps]').forEach(b=>b.onclick=()=>chooseRps(b.dataset.rps))}
function openRps(){buildRpsModal();G.phase='rps';G.rps={red:null,blue:null};$('rpsTitle').textContent=G.lang==='zh'?'石头剪刀布 · 决定第一轮先攻':'Rock Paper Scissors · Decide First Offense';$('rpsText').textContent=G.mode==='single'?(G.lang==='zh'?'你代表红队选择；电脑蓝队会同时随机出拳。平局就再来一次。':'Choose for Red Team; Blue computer chooses randomly. A tie repeats.'):(G.lang==='zh'?'红队先秘密选择，然后交给蓝队选择。平局重来。':'Red chooses first in secret, then Blue chooses. A tie repeats.');$('rpsModal').classList.add('show');renderAll()}
function chooseRps(choice){if(G.mode==='single'){const cpu=['rock','paper','scissors'][Math.floor(Math.random()*3)],w=rpsWinner(choice,cpu);$('rpsText').innerHTML=(G.lang==='zh'?`红队：${rpsName(choice)}　电脑蓝队：${rpsName(cpu)}<br>`:`Red: ${rpsName(choice)}　Blue computer: ${rpsName(cpu)}<br>`)+(w?(G.lang==='zh'?`<b>${teamName(w)}获胜，第一轮先攻！</b>`:`<b>${teamName(w)} wins and attacks first!</b>`):(G.lang==='zh'?'<b>平局，再选一次。</b>':'<b>Tie. Choose again.</b>'));if(!w)return;addLog(G.lang==='zh'?`<b>石头剪刀布：</b>${teamName(w)}获胜，获得第一轮先攻。`:`<b>Rock-Paper-Scissors:</b> ${teamName(w)} wins first offense.`);setTimeout(()=>{$('rpsModal').classList.remove('show');beginRound(w)},650);return}
 if(!G.rps.red){G.rps.red=choice;$('rpsModal').classList.remove('show');handoff('blue',G.lang==='zh'?'轮到蓝队选择':'Blue Team chooses',G.lang==='zh'?'红队已经秘密选择，请把设备交给蓝队。':'Red has chosen. Hand the device to Blue.',()=>{G.phase='rps';$('rpsText').textContent=G.lang==='zh'?'蓝队请选择石头、剪刀或布。':'Blue: choose Rock, Paper, or Scissors.';$('rpsModal').classList.add('show')});return}
 G.rps.blue=choice;const w=rpsWinner(G.rps.red,G.rps.blue);if(!w){G.rps={red:null,blue:null};$('rpsText').innerHTML=G.lang==='zh'?'<b>平局！重新开始，红队先选。</b>':'<b>Tie! Start again with Red choosing first.</b>';setTimeout(()=>{G.currentTeam='red';G.currentIndex=firstIndex('red');$('rpsText').textContent=G.lang==='zh'?'红队请选择。':'Red Team: choose.'},700);return}addLog(G.lang==='zh'?`<b>石头剪刀布：</b>${teamName(w)}获胜，获得第一轮先攻。`:`<b>Rock-Paper-Scissors:</b> ${teamName(w)} wins first offense.`);setTimeout(()=>{$('rpsModal').classList.remove('show');beginRound(w)},650)}
function start(){createGame();$('setupModal').classList.remove('show');updateStatic();renderAll();openRps()}
document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-size]').forEach(x=>x.classList.remove('active'));b.classList.add('active');G.size=Number(b.dataset.size)});document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-view]').forEach(x=>x.classList.remove('active'));b.classList.add('active');G.mode=b.dataset.view});$('startBtn').onclick=start;$('restartBtn').onclick=()=>location.reload();$('langToggleBtn').onclick=()=>{G.lang=G.lang==='zh'?'en':'zh';updateStatic();if(G.players.length)renderAll();if($('rpsModal')&&$('rpsModal').classList.contains('show'))openRps()};$('rulesBtn').onclick=()=>$('rulesModal').classList.add('show');$('closeRulesBtn').onclick=()=>$('rulesModal').classList.remove('show');$('nextBtn').onclick=()=>cycle(1);$('prevBtn').onclick=()=>cycle(-1);$('useSkillBtn').onclick=()=>skillDecision(true);$('skipSkillBtn').onclick=()=>skillDecision(false);updateStatic();$('modeText').textContent=tx('drive');
})();