(()=>{
const zh=`<div class="guideDoc">
<div class="guideLead"><b>🏈 玩法说明：完整攻防流程</b><br>这里专门解释每一次进攻怎么出牌、对方怎么防守、什么时候成功、什么时候失败、什么时候换球权。</div>
<div class="guideToc">
<a href="#g-run">RUN流程</a><a href="#g-pass">PASS流程</a><a href="#g-qb">QB技能</a><a href="#g-defense">防守流程</a><a href="#g-result">成功/失败</a><a href="#g-possession">换球权</a><a href="#g-round">回合结束</a><a href="#g-td">TOUCHDOWN</a>
</div>
<section id="g-run"><h3>1. RUN 完整流程</h3><p><b>持球者出 RUN 🏃 → 防守方行动。</b></p><p>防守方可以：<b>不防守 / TACKLE / BLITZ</b>。</p><div class="chain">RUN → 不防守 = ✅ 成功，推进1格</div><div class="chain">RUN → BLITZ = ❌ 失败，不推进</div><div class="chain">RUN → TACKLE → 不用BLOCK = ❌ 失败</div><div class="chain">RUN → TACKLE → BLOCK → 不用BLITZ = ✅ 成功</div><div class="chain">RUN → TACKLE → BLOCK → BLITZ = ❌ 失败</div><p>TACKLE只阻止RUN，<b>不会自动抢走球</b>。RUN成功后，原持球者继续持球。</p></section>
<section id="g-pass"><h3>2. PASS 完整流程</h3><p><b>持球者出 PASS 🎯 → 选择一名队友接球 → 如果是QB先决定技能 → 防守方行动。</b></p><p>防守方可以：<b>不防守 / INTERCEPTION / BLITZ</b>。</p><div class="chain">PASS → 不防守 = ✅ 成功，接球队友持球，推进1格</div><div class="chain">PASS → BLITZ = ❌ 失败，不推进</div><div class="chain">PASS → INTERCEPTION → 不用BLOCK = 🦅 抄截成功，防守方获得球权</div><div class="chain">PASS → INTERCEPTION → BLOCK → 不用BLITZ = ✅ PASS成功</div><div class="chain">PASS → INTERCEPTION → BLOCK → BLITZ = ❌ PASS失败</div></section>
<section id="g-qb"><h3>3. QB 身份技能</h3><p>只有<b>QB打出PASS</b>并且技能还没使用时，系统才会弹出技能选择。</p><p>选择<b>暂不使用</b>：技能保留。选择<b>使用技能</b>：技能立即消耗。</p><p>如果PASS最终成功，本次推进<b>2格</b>。如果之后被INTERCEPTION或BLITZ阻止，技能也<b>不会返还</b>。</p></section>
<section id="g-defense"><h3>4. 当对方进攻时，你怎么防守</h3><p>对方出<b>RUN</b>：你可以出 <b>TACKLE / BLITZ / 不防守</b>。</p><p>对方出<b>PASS</b>：你可以出 <b>INTERCEPTION / BLITZ / 不防守</b>。</p><p>你的TACKLE或INTERCEPTION如果被BLOCK取消，你还有最后一次机会出<b>BLITZ</b>。</p><p>单人模式下，蓝队进攻由电脑自动选择RUN/PASS；你只负责红队的防守决定。</p></section>
<section id="g-result"><h3>5. 什么叫成功？什么叫失败？</h3><p><b>✅ 进攻成功：</b>整条攻防链结束后，RUN/PASS没有被最终阻止。系统自动推进，不需要手动+1。</p><p><b>❌ 进攻失败：</b>被TACKLE、BLITZ或其他最终有效防守阻止。场地位置不前进。</p><p><b>🦅 抄截成功：</b>INTERCEPTION最终没有被BLOCK取消，出INTERCEPTION的防守球员直接获得球权。</p></section>
<section id="g-possession"><h3>6. 什么时候换球权</h3><p>INTERCEPTION成功 → 立即换球权。</p><p>当前队伍所有球员都没有RUN/PASS，而另一队还有RUN/PASS → 球权交给另一队。</p><p>当前持球者没RUN/PASS，但同队其他人还有 → 不是换队，而是重新选择同队持球者。</p></section>
<section id="g-round"><h3>7. 一轮什么时候结束</h3><p>当红蓝双方都没有RUN/PASS可以继续进攻时，本轮结束。</p><p>系统统一收回手牌、弃牌和牌库，洗牌后重新发牌。<b>不是出一张就补一张。</b></p><p>普通回合结束时，已经推进的码线位置保留。</p></section>
<section id="g-td"><h3>8. TOUCHDOWN 与获胜</h3><p><b>50是起点，不算成功。</b></p><p>第1次成功：50→40<br>第2次：40→30<br>第3次：30→20<br>第4次：20→10，然后持球者自动冲入END ZONE。</p><p>第4次成功直接TOUCHDOWN，<b>不需要第5次进攻</b>。每次TOUCHDOWN获得1个🏈，先拿3个🏈获胜。</p></section>
</div>`;
const en=`<div class="guideDoc">
<div class="guideLead"><b>🏈 HOW TO PLAY: COMPLETE OFFENSE & DEFENSE FLOW</b><br>This section explains exactly how each play works, how the defense answers, when a play succeeds or fails, and when possession changes.</div>
<div class="guideToc"><a href="#g-run">RUN Flow</a><a href="#g-pass">PASS Flow</a><a href="#g-qb">QB Skill</a><a href="#g-defense">Defense</a><a href="#g-result">Success / Fail</a><a href="#g-possession">Possession</a><a href="#g-round">Round End</a><a href="#g-td">Touchdown</a></div>
<section id="g-run"><h3>1. Complete RUN flow</h3><p><b>Ball carrier plays RUN 🏃 → defense responds.</b></p><p>Defense may choose <b>No Defense / TACKLE / BLITZ</b>.</p><div class="chain">RUN → No Defense = ✅ success, advance 1 space</div><div class="chain">RUN → BLITZ = ❌ fail</div><div class="chain">RUN → TACKLE → No BLOCK = ❌ fail</div><div class="chain">RUN → TACKLE → BLOCK → No BLITZ = ✅ success</div><div class="chain">RUN → TACKLE → BLOCK → BLITZ = ❌ fail</div><p>TACKLE stops a RUN but <b>does not automatically steal possession</b>. After a successful RUN, the same player keeps the ball.</p></section>
<section id="g-pass"><h3>2. Complete PASS flow</h3><p><b>Ball carrier plays PASS 🎯 → choose a teammate receiver → QB skill decision if available → defense responds.</b></p><p>Defense may choose <b>No Defense / INTERCEPTION / BLITZ</b>.</p><div class="chain">PASS → No Defense = ✅ success; receiver takes the ball; advance 1</div><div class="chain">PASS → BLITZ = ❌ fail</div><div class="chain">PASS → INTERCEPTION → No BLOCK = 🦅 interception; defense takes possession</div><div class="chain">PASS → INTERCEPTION → BLOCK → No BLITZ = ✅ PASS succeeds</div><div class="chain">PASS → INTERCEPTION → BLOCK → BLITZ = ❌ PASS fails</div></section>
<section id="g-qb"><h3>3. QB role skill</h3><p>The skill prompt appears only when the <b>QB plays PASS</b> and the skill is unused.</p><p><b>Skip:</b> keep the skill. <b>Use:</b> consume it immediately.</p><p>If the PASS finally succeeds, advance <b>2 spaces</b>. If the PASS is later stopped, the used skill is <b>not refunded</b>.</p></section>
<section id="g-defense"><h3>4. How to defend</h3><p>Against <b>RUN</b>: TACKLE / BLITZ / No Defense.</p><p>Against <b>PASS</b>: INTERCEPTION / BLITZ / No Defense.</p><p>If your TACKLE or INTERCEPTION is canceled by BLOCK, you still get one final chance to use <b>BLITZ</b>.</p><p>In Solo Mode, Blue chooses its offense automatically; you only make Red Team's defense choices.</p></section>
<section id="g-result"><h3>5. Success, failure, and interception</h3><p><b>✅ Success:</b> the full response chain ends without a final stop. The system advances automatically.</p><p><b>❌ Failure:</b> the final defense stops the play. No field progress.</p><p><b>🦅 Interception:</b> INTERCEPTION survives the response chain; that defender takes possession.</p></section>
<section id="g-possession"><h3>6. When possession changes</h3><p>Successful INTERCEPTION → possession changes immediately.</p><p>If one entire team has no RUN/PASS but the other team does → possession goes to the other team.</p><p>If only the current ball carrier has no RUN/PASS but a teammate does → choose a new ball carrier on the same team.</p></section>
<section id="g-round"><h3>7. When a round ends</h3><p>The round ends when neither team has a RUN/PASS available.</p><p>The game gathers all cards, shuffles, and redeals. <b>You do not draw a replacement after every card.</b></p><p>Normal round endings do not erase field progress.</p></section>
<section id="g-td"><h3>8. TOUCHDOWN and winning</h3><p><b>The 50 is only the starting point.</b></p><p>1st success: 50→40<br>2nd: 40→30<br>3rd: 30→20<br>4th: 20→10, then the ball carrier automatically runs into the END ZONE.</p><p>The 4th success scores the TOUCHDOWN—<b>there is no 5th play</b>. Each TOUCHDOWN earns 1 🏈; first to 3 🏈 wins.</p></section>
</div>`;
function css(){if(document.getElementById('guideDocStyle'))return;const s=document.createElement('style');s.id='guideDocStyle';s.textContent=`.guideDoc{font-size:14px;line-height:1.65}.guideLead{background:#152417;border:1px solid #5f7d64;border-radius:12px;padding:12px;margin:8px 0 12px}.guideToc{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin:10px 0 14px;position:sticky;top:-12px;background:#101a12;padding:8px;z-index:5;border-radius:10px}.guideToc a{background:#285c36;color:#fff;text-decoration:none;border-radius:8px;padding:8px;font-weight:900;text-align:center;font-size:12px}.guideDoc section{scroll-margin-top:90px;background:#152017;border:1px solid #405b46;border-radius:12px;padding:11px;margin:10px 0}.guideDoc h3{margin:0 0 7px;color:#f0cf78}.guideDoc p{margin:6px 0}.chain{background:#0d160f;border-left:4px solid #d7b45a;padding:7px 9px;margin:5px 0;border-radius:6px}@media(min-width:700px){.guideToc{grid-template-columns:repeat(4,minmax(0,1fr))}}`;document.head.appendChild(s)}
function apply(){css();const el=document.getElementById('rulesBody');if(!el)return;const isEn=(document.documentElement.lang||'').toLowerCase().startsWith('en');el.innerHTML=isEn?en:zh;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{apply();const b=document.getElementById('langToggleBtn');if(b)b.addEventListener('click',()=>setTimeout(apply,20));const r=document.getElementById('rulesBtn');if(r)r.addEventListener('click',()=>setTimeout(apply,20));});else apply();
})();