(()=>{
const manual={
zh:`<div class="manualDoc"><div class="manualLead"><b>🏈 策略模式 · 单人模式完整说明书</b><br>按整场游戏真正发生的顺序阅读。上面的目录可以直接跳到你想看的部分。</div>
<div class="keyRule"><b>🏈 重要：橄榄球本身是一张 FOOTBALL CARD（橄榄球卡），不是额外棋子。</b><br>第一轮先攻确定后，先攻方获得这张橄榄球卡。游戏里说“持球者”，就是当前拿着这张橄榄球卡的球员。整场比赛始终只有这一张橄榄球卡代表球权。</div>
<div class="manualToc"><a href="#m-setup">1 开局与分队</a><a href="#m-rps">2 石头剪刀布</a><a href="#m-deal">3 发牌</a><a href="#m-round">4 每轮开始</a><a href="#m-run">5 RUN流程</a><a href="#m-pass">6 PASS流程</a><a href="#m-defense">7 防守流程</a><a href="#m-result">8 成功/失败</a><a href="#m-possession">9 换球权</a><a href="#m-redeal">10 回合结束</a><a href="#m-td">11 TOUCHDOWN</a><a href="#m-win">12 获胜</a></div>
<section id="m-setup"><h3>1. 开局与分队</h3><p>先选择 <b>2v2 / 3v3 / 4v4</b>。</p><p>2v2：红2人 vs 蓝2人，每人7张牌。<br>3v3：红3人 vs 蓝3人，每人6张牌。<br>4v4：红4人 vs 蓝4人，每人5张牌。</p><p><b>单人模式：</b>你只控制红队，蓝队由电脑控制。每队系统分配1名QB，其余为普通球员。</p><p><b>FOOTBALL CARD：</b>它单独代表球权，不算普通功能牌，也不是玩家随意打出的牌。谁拿着这张牌，谁就是当前持球者。</p><p>QB只有一次身份技能：QB打出PASS、选好接球人后，可以决定是否使用。使用后如果PASS最终成功，本次推进2格；如果最终失败，技能也不会返还。</p></section>
<section id="m-rps"><h3>2. 第一轮先攻：石头剪刀布</h3><p>正式开局先用<b>石头剪刀布</b>决定第一轮谁拿球、谁先进攻。</p><p>你代表红队选择：✊石头 / 🖐️布 / ✌️剪刀；电脑蓝队随机选择。</p><p>你赢 → 红队第一轮先攻并获得FOOTBALL CARD。<br>电脑赢 → 蓝队第一轮先攻并获得FOOTBALL CARD。<br>平局 → 重新选择，直到分出胜负。</p><div class="keyRule">只有第一轮用石头剪刀布。之后每轮先攻方交替。</div></section>
<section id="m-deal"><h3>3. 发牌规则</h3><p>系统洗牌并按人数发功能牌：2v2每人7张，3v3每人6张，4v4每人5张。</p><p>功能牌包括：<b>RUN、PASS、TACKLE、INTERCEPTION、BLOCK、BLITZ</b>。</p><p><b>FOOTBALL CARD不属于这批普通手牌。</b>它单独跟随当前持球者，用来表示球权。</p><div class="warning">不是“出一张就马上补一张”。本轮使用现有手牌；本轮结束后才统一收牌、洗牌、重新发牌。</div></section>
<section id="m-round"><h3>4. 每轮开始要做什么</h3><p>先攻方先选择一名<b>手里有RUN或PASS</b>的球员作为持球者，并让该球员持有FOOTBALL CARD。</p><p>只有当前持球者可以发动下一次进攻。</p><ol><li>持球者选择RUN或PASS</li><li>PASS时选择接球队友</li><li>QB打PASS时决定是否使用技能</li><li>防守方选择防守牌或不防守</li><li>遇到TACKLE/INTERCEPTION时，进攻方决定是否BLOCK</li><li>BLOCK后防守方可决定是否BLITZ</li><li>系统自动结算成功、失败、推进或换球权</li></ol></section>
<section id="m-run"><h3>5. RUN 完整流程</h3><div class="comboChain">RUN → 不防守 = ✅ 成功 → 推进1格</div><div class="comboChain">RUN → BLITZ = ❌ 失败</div><div class="comboChain">RUN → TACKLE → 不BLOCK = ❌ 失败</div><div class="comboChain">RUN → TACKLE → BLOCK → 不BLITZ = ✅ 成功</div><div class="comboChain">RUN → TACKLE → BLOCK → BLITZ = ❌ 失败</div><p>RUN成功后，<b>FOOTBALL CARD仍留在原持球者那里</b>。TACKLE只阻止RUN，不会自动把橄榄球卡抢走。</p></section>
<section id="m-pass"><h3>6. PASS 完整流程</h3><p>持球者出PASS后，先选择同队接球人。</p><div class="comboChain">PASS → 不防守 = ✅ 成功</div><div class="comboChain">PASS → BLITZ = ❌ 失败</div><div class="comboChain">PASS → INTERCEPTION → 不BLOCK = 🦅 抄截成功，换球权</div><div class="comboChain">PASS → INTERCEPTION → BLOCK → 不BLITZ = ✅ 成功</div><div class="comboChain">PASS → INTERCEPTION → BLOCK → BLITZ = ❌ 失败</div><p><b>PASS成功：</b>把FOOTBALL CARD交给你选择的接球队友，他成为新的持球者。</p></section>
<section id="m-defense"><h3>7. 防守流程</h3><p>对方出RUN → TACKLE / BLITZ / 不防守。</p><p>对方出PASS → INTERCEPTION / BLITZ / 不防守。</p><p>如果TACKLE或INTERCEPTION被BLOCK取消，防守方还可用BLITZ做最后反制。</p></section>
<section id="m-result"><h3>8. 成功和失败怎么判定</h3><p><b>✅ 成功：</b>完整攻防链结束后没有被最终阻止，系统自动推进。</p><p><b>❌ 失败：</b>被最终有效防守阻止，不推进。</p><p><b>🦅 抄截成功：</b>把FOOTBALL CARD交给成功使用INTERCEPTION的防守球员，他立即成为新持球者。</p><div class="keyRule">成功/失败由系统自动结算，不需要手动+1。</div></section>
<section id="m-possession"><h3>9. 换球权或换持球者</h3><p>INTERCEPTION成功 → FOOTBALL CARD直接转移给抄截球员，立即换球权。</p><p>当前持球者没有RUN/PASS，但同队其他球员还有 → 同队重新选持球者，并把FOOTBALL CARD交给新持球者。</p><p>整支当前队伍都没有RUN/PASS，但另一队还有 → 球权交给另一队，由另一队选择持球者。</p></section>
<section id="m-redeal"><h3>10. 一轮什么时候结束</h3><p>当红蓝双方都没有RUN/PASS可以继续进攻时，本轮结束。</p><p>系统统一收回功能牌、洗牌并重新发牌。FOOTBALL CARD继续作为独立球权牌处理。</p><p>下一轮由上一轮先攻方的对手先攻。</p><div class="keyRule">普通轮次结束不会清除已经推进的码线位置。</div></section>
<section id="m-td"><h3>11. TOUCHDOWN</h3><p>50码只是起点。第1次成功50→40，第2次40→30，第3次30→20，第4次20→10，然后持球者自动冲入END ZONE。</p><p>第4次成功后直接TOUCHDOWN，获得1个🏈，不需要第5次进攻。</p></section>
<section id="m-win"><h3>12. 怎么赢</h3><p><b>先获得3个🏈的队伍立即获胜。</b></p></section></div>`,
en:`<div class="manualDoc"><div class="manualLead"><b>🏈 STRATEGY MODE · SOLO MODE COMPLETE RULEBOOK</b><br>Read the game in its real order. Use the menu below to jump to any section.</div>
<div class="keyRule"><b>🏈 IMPORTANT: The football itself is a FOOTBALL CARD, not a separate game piece.</b><br>After first possession is decided, the team on offense receives this Football Card. A “ball carrier” is the player currently holding it. There is only one Football Card representing possession during the game.</div>
<div class="manualToc"><a href="#m-setup">1 Setup & Teams</a><a href="#m-rps">2 Rock-Paper-Scissors</a><a href="#m-deal">3 Deal</a><a href="#m-round">4 Round Start</a><a href="#m-run">5 RUN Flow</a><a href="#m-pass">6 PASS Flow</a><a href="#m-defense">7 Defense</a><a href="#m-result">8 Success / Fail</a><a href="#m-possession">9 Possession</a><a href="#m-redeal">10 Round End</a><a href="#m-td">11 Touchdown</a><a href="#m-win">12 Win</a></div>
<section id="m-setup"><h3>1. Setup and teams</h3><p>Choose <b>2v2 / 3v3 / 4v4</b>.</p><p>2v2: 7 cards each. 3v3: 6 cards each. 4v4: 5 cards each.</p><p><b>Solo Mode:</b> you control Red; the computer controls Blue. Each team has one QB.</p><p><b>FOOTBALL CARD:</b> it represents possession. It is not a normal Action Card and is not played like RUN, PASS, or Defense cards.</p></section>
<section id="m-rps"><h3>2. First offense: Rock-Paper-Scissors</h3><p>Red and Blue use Rock-Paper-Scissors to decide Round 1 first offense. The winner receives the Football Card.</p><div class="keyRule">Only Round 1 uses Rock-Paper-Scissors. First offense alternates after that.</div></section>
<section id="m-deal"><h3>3. Deal cards</h3><p>Deal normal Action Cards by team size: RUN, PASS, TACKLE, INTERCEPTION, BLOCK, BLITZ.</p><p><b>The Football Card is separate from these normal hands</b> and follows the current ball carrier.</p><div class="warning">Do not draw a replacement after every card. Redeal only when the round ends.</div></section>
<section id="m-round"><h3>4. Start each round</h3><p>The team on offense chooses a player with RUN or PASS as the ball carrier and gives that player the Football Card.</p><ol><li>Ball carrier chooses RUN or PASS</li><li>Choose receiver for PASS</li><li>QB skill decision if available</li><li>Defense responds</li><li>Offense may BLOCK</li><li>Defense may use final BLITZ</li><li>System resolves the result</li></ol></section>
<section id="m-run"><h3>5. RUN flow</h3><div class="comboChain">RUN → No Defense = ✅ success</div><div class="comboChain">RUN → BLITZ = ❌ fail</div><div class="comboChain">RUN → TACKLE → No BLOCK = ❌ fail</div><div class="comboChain">RUN → TACKLE → BLOCK → No BLITZ = ✅ success</div><div class="comboChain">RUN → TACKLE → BLOCK → BLITZ = ❌ fail</div><p>After a successful RUN, <b>the Football Card stays with the same ball carrier</b>.</p></section>
<section id="m-pass"><h3>6. PASS flow</h3><div class="comboChain">PASS → No Defense = ✅ success</div><div class="comboChain">PASS → BLITZ = ❌ fail</div><div class="comboChain">PASS → INTERCEPTION → No BLOCK = 🦅 interception</div><div class="comboChain">PASS → INTERCEPTION → BLOCK → No BLITZ = ✅ success</div><div class="comboChain">PASS → INTERCEPTION → BLOCK → BLITZ = ❌ fail</div><p>After a successful PASS, <b>move the Football Card to the chosen receiver</b>.</p></section>
<section id="m-defense"><h3>7. Defense</h3><p>Against RUN: TACKLE / BLITZ / No Defense.</p><p>Against PASS: INTERCEPTION / BLITZ / No Defense.</p></section>
<section id="m-result"><h3>8. Success and failure</h3><p><b>✅ Success:</b> advance automatically.</p><p><b>❌ Failure:</b> no advance.</p><p><b>🦅 Successful INTERCEPTION:</b> move the Football Card to the defender who made the interception; possession changes immediately.</p></section>
<section id="m-possession"><h3>9. Possession</h3><p>INTERCEPTION → Football Card moves to the defender.</p><p>New ball carrier on the same team → move the Football Card to that teammate.</p></section>
<section id="m-redeal"><h3>10. Round end</h3><p>When neither team has RUN/PASS left, gather and redeal the normal Action Cards. The Football Card remains the separate possession card.</p></section>
<section id="m-td"><h3>11. Touchdown</h3><p>50→40→30→20→10, then the ball carrier automatically runs into the END ZONE. The 4th success scores the TOUCHDOWN.</p></section>
<section id="m-win"><h3>12. Win</h3><p><b>First team to collect 3 🏈 wins.</b></p></section></div>`};
function addStyle(){if(document.getElementById('manualDocStyle'))return;const s=document.createElement('style');s.id='manualDocStyle';s.textContent=`.manualDoc{font-size:14px;line-height:1.65}.manualLead{background:#2b2715;border:2px solid #b99b4b;border-radius:12px;padding:11px;margin:6px 0 10px}.manualToc{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px;margin:10px 0 14px;position:sticky;top:-12px;background:#101a12;padding:8px;z-index:8;border-radius:10px}.manualToc a{background:#244f31;color:#fff;text-decoration:none;border-radius:8px;padding:8px 5px;font-size:11px;font-weight:900;text-align:center}.manualDoc section{scroll-margin-top:95px;background:#152017;border:1px solid #405b46;border-radius:12px;padding:11px;margin:10px 0}.manualDoc h3{margin:0 0 7px;color:#f0cf78;font-size:17px}.manualDoc p,.manualDoc li{margin:5px 0}.manualDoc ol{padding-left:21px}.keyRule{background:#302914;border:1px solid #b99b4b;border-radius:9px;padding:8px;margin:7px 0;font-weight:900}.warning{background:#321a1a;border-left:5px solid #b94c4c;border-radius:8px;padding:8px;margin:7px 0;font-weight:850}.comboChain{background:#0c1510;border-left:4px solid #d0ae55;border-radius:7px;padding:8px;margin:6px 0;font-weight:850}@media(min-width:700px){.manualToc{grid-template-columns:repeat(4,minmax(0,1fr))}}`;document.head.appendChild(s)}
function getLang(){return (document.documentElement.lang||'zh').toLowerCase().startsWith('en')?'en':'zh'}
function render(){const lang=getLang(),btn=document.getElementById('manualBtn');if(!btn)return;btn.textContent=lang==='en'?'RULEBOOK':'说明书';document.getElementById('manualHeading').textContent=lang==='en'?'Strategy Mode Rulebook':'策略模式说明书';document.getElementById('closeManualBtn').textContent=lang==='en'?'Close':'关闭';document.getElementById('manualBody').innerHTML=manual[lang]}
function build(){addStyle();const top=document.querySelector('.topbar > div:last-child');if(!top||document.getElementById('manualBtn'))return;const btn=document.createElement('button');btn.className='btn';btn.id='manualBtn';top.insertBefore(btn,document.getElementById('rulesBtn'));const modal=document.createElement('div');modal.className='modal';modal.id='manualModal';modal.innerHTML='<div class="modalBox"><div style="display:flex;justify-content:space-between;gap:8px;align-items:center"><h2 style="margin:0" id="manualHeading"></h2><button class="btn" id="closeManualBtn"></button></div><div id="manualBody" style="margin-top:10px;color:#dbe5de"></div></div>';document.body.appendChild(modal);btn.onclick=()=>{render();modal.classList.add('show');modal.querySelector('.modalBox').scrollTop=0};document.getElementById('closeManualBtn').onclick=()=>modal.classList.remove('show');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.remove('show')});const langBtn=document.getElementById('langToggleBtn');if(langBtn)langBtn.addEventListener('click',()=>setTimeout(render,30));render()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();