(()=>{
const zh=`<div class="guideDoc"><div class="guideLead"><b>🏈 玩法说明：完整攻防流程</b><br>这里专门解释每一次进攻怎么出牌、对方怎么防守、什么时候成功、什么时候失败、什么时候换球权。</div>
<div class="guideNote"><b>🏈 先记住：橄榄球本身是一张 FOOTBALL CARD（橄榄球卡）。</b><br>这张卡单独代表球权，不是普通功能牌。谁拿着FOOTBALL CARD，谁就是当前持球者。RUN成功后卡留在原持球者；PASS成功后把卡交给接球人；INTERCEPTION成功后把卡交给抄截球员。</div>
<div class="guideToc"><a href="#g-run">RUN流程</a><a href="#g-pass">PASS流程</a><a href="#g-qb">QB技能</a><a href="#g-defense">防守流程</a><a href="#g-result">成功/失败</a><a href="#g-possession">换球权</a><a href="#g-round">回合结束</a><a href="#g-td">TOUCHDOWN</a></div>
<section id="g-run"><h3>1. RUN 完整流程</h3><p><b>当前拿着FOOTBALL CARD的持球者出 RUN 🏃 → 防守方行动。</b></p><p>防守方可以：<b>不防守 / TACKLE / BLITZ</b>。</p><div class="chain">RUN → 不防守 = ✅ 成功，推进1格</div><div class="chain">RUN → BLITZ = ❌ 失败，不推进</div><div class="chain">RUN → TACKLE → 不用BLOCK = ❌ 失败</div><div class="chain">RUN → TACKLE → BLOCK → 不用BLITZ = ✅ 成功</div><div class="chain">RUN → TACKLE → BLOCK → BLITZ = ❌ 失败</div><p>RUN成功后，<b>FOOTBALL CARD继续留在原持球者</b>。TACKLE只阻止RUN，不会自动抢走球权卡。</p></section>
<section id="g-pass"><h3>2. PASS 完整流程</h3><p><b>持球者出 PASS 🎯 → 选择一名队友接球 → 如果是QB先决定技能 → 防守方行动。</b></p><div class="chain">PASS → 不防守 = ✅ 成功，FOOTBALL CARD交给接球人，推进1格</div><div class="chain">PASS → BLITZ = ❌ 失败，不推进</div><div class="chain">PASS → INTERCEPTION → 不用BLOCK = 🦅 抄截成功，FOOTBALL CARD交给防守球员</div><div class="chain">PASS → INTERCEPTION → BLOCK → 不用BLITZ = ✅ PASS成功</div><div class="chain">PASS → INTERCEPTION → BLOCK → BLITZ = ❌ PASS失败</div></section>
<section id="g-qb"><h3>3. QB 身份技能</h3><p>只有<b>QB打出PASS</b>并且技能还没使用时，系统才会弹出技能选择。</p><p>暂不使用：技能保留。使用：技能立即消耗。</p><p>PASS最终成功，本次推进2格；如果后来失败，技能不返还。</p></section>
<section id="g-defense"><h3>4. 当对方进攻时怎么防守</h3><p>对方出RUN：TACKLE / BLITZ / 不防守。</p><p>对方出PASS：INTERCEPTION / BLITZ / 不防守。</p><p>TACKLE或INTERCEPTION被BLOCK取消后，还有最后一次BLITZ机会。</p></section>
<section id="g-result"><h3>5. 成功、失败、抄截</h3><p><b>✅ 成功：</b>系统自动推进。</p><p><b>❌ 失败：</b>不推进。</p><p><b>🦅 抄截成功：</b>FOOTBALL CARD直接转移给成功抄截的防守球员，立即换球权。</p></section>
<section id="g-possession"><h3>6. 什么时候换球权</h3><p>INTERCEPTION成功 → FOOTBALL CARD转移到防守方。</p><p>同队换持球者 → FOOTBALL CARD交给新的同队持球者。</p><p>整队没有RUN/PASS而另一队还有 → 球权交给另一队。</p></section>
<section id="g-round"><h3>7. 一轮什么时候结束</h3><p>当红蓝双方都没有RUN/PASS可以继续进攻时，本轮结束。</p><p>系统统一收回和重发普通功能牌；<b>FOOTBALL CARD始终作为独立球权卡处理</b>。</p></section>
<section id="g-td"><h3>8. TOUCHDOWN 与获胜</h3><p>50是起点。第1次成功50→40，第2次40→30，第3次30→20，第4次20→10，然后持球者自动冲入END ZONE。</p><p>第4次成功直接TOUCHDOWN，每次TOUCHDOWN获得1个🏈，先拿3个🏈获胜。</p></section></div>`;
const en=`<div class="guideDoc"><div class="guideLead"><b>🏈 HOW TO PLAY: COMPLETE OFFENSE & DEFENSE FLOW</b><br>This section explains exactly how each play works, when it succeeds or fails, and when possession changes.</div>
<div class="guideNote"><b>🏈 First, remember: the football itself is a FOOTBALL CARD.</b><br>This card represents possession and is separate from the normal Action Cards. The player holding it is the ball carrier. Successful RUN: keep it with the same player. Successful PASS: move it to the receiver. Successful INTERCEPTION: move it to the defender.</div>
<div class="guideToc"><a href="#g-run">RUN Flow</a><a href="#g-pass">PASS Flow</a><a href="#g-qb">QB Skill</a><a href="#g-defense">Defense</a><a href="#g-result">Success / Fail</a><a href="#g-possession">Possession</a><a href="#g-round">Round End</a><a href="#g-td">Touchdown</a></div>
<section id="g-run"><h3>1. Complete RUN flow</h3><p>The player holding the Football Card plays RUN.</p><div class="chain">RUN → No Defense = ✅ success</div><div class="chain">RUN → BLITZ = ❌ fail</div><div class="chain">RUN → TACKLE → No BLOCK = ❌ fail</div><div class="chain">RUN → TACKLE → BLOCK → No BLITZ = ✅ success</div><div class="chain">RUN → TACKLE → BLOCK → BLITZ = ❌ fail</div><p>After a successful RUN, <b>the Football Card stays with the same ball carrier</b>.</p></section>
<section id="g-pass"><h3>2. Complete PASS flow</h3><div class="chain">PASS → No Defense = ✅ success; move Football Card to receiver</div><div class="chain">PASS → BLITZ = ❌ fail</div><div class="chain">PASS → INTERCEPTION → No BLOCK = 🦅 interception; move Football Card to defender</div><div class="chain">PASS → INTERCEPTION → BLOCK → No BLITZ = ✅ success</div><div class="chain">PASS → INTERCEPTION → BLOCK → BLITZ = ❌ fail</div></section>
<section id="g-qb"><h3>3. QB skill</h3><p>The QB skill appears only after an unused QB plays PASS. If used and the PASS succeeds, advance 2 spaces. A failed play does not refund the skill.</p></section>
<section id="g-defense"><h3>4. Defense</h3><p>Against RUN: TACKLE / BLITZ / No Defense.</p><p>Against PASS: INTERCEPTION / BLITZ / No Defense.</p></section>
<section id="g-result"><h3>5. Success, failure, interception</h3><p><b>✅ Success:</b> advance automatically.</p><p><b>❌ Failure:</b> no advance.</p><p><b>🦅 Interception:</b> move the Football Card to the defender; possession changes immediately.</p></section>
<section id="g-possession"><h3>6. Possession</h3><p>The Football Card always shows who has possession. Move it whenever the ball carrier changes.</p></section>
<section id="g-round"><h3>7. Round end</h3><p>Redeal the normal Action Cards when neither team has RUN/PASS left. The Football Card remains the separate possession card.</p></section>
<section id="g-td"><h3>8. Touchdown and winning</h3><p>50→40→30→20→10→END ZONE. The 4th success scores a TOUCHDOWN. First to 3 🏈 wins.</p></section></div>`;
function css(){if(document.getElementById('guideDocStyle'))return;const s=document.createElement('style');s.id='guideDocStyle';s.textContent=`.guideDoc{font-size:14px;line-height:1.65}.guideLead,.guideNote{background:#152417;border:1px solid #5f7d64;border-radius:12px;padding:12px;margin:8px 0 12px}.guideNote{background:#302914;border-color:#b99b4b}.guideToc{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin:10px 0 14px;position:sticky;top:-12px;background:#101a12;padding:8px;z-index:5;border-radius:10px}.guideToc a{background:#285c36;color:#fff;text-decoration:none;border-radius:8px;padding:8px;font-weight:900;text-align:center;font-size:12px}.guideDoc section{scroll-margin-top:90px;background:#152017;border:1px solid #405b46;border-radius:12px;padding:11px;margin:10px 0}.guideDoc h3{margin:0 0 7px;color:#f0cf78}.guideDoc p{margin:6px 0}.chain{background:#0d160f;border-left:4px solid #d7b45a;padding:7px 9px;margin:5px 0;border-radius:6px}@media(min-width:700px){.guideToc{grid-template-columns:repeat(4,minmax(0,1fr))}}`;document.head.appendChild(s)}
function apply(){css();const el=document.getElementById('rulesBody');if(!el)return;const isEn=(document.documentElement.lang||'').toLowerCase().startsWith('en');el.innerHTML=isEn?en:zh;}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{apply();const b=document.getElementById('langToggleBtn');if(b)b.addEventListener('click',()=>setTimeout(apply,20));const r=document.getElementById('rulesBtn');if(r)r.addEventListener('click',()=>setTimeout(apply,20));});else apply();
})();